espresso-cash/espresso-cash-public

- lib/src/solana_wallet.dart
- lib/src/types/hd_key_pair.dart
- test/solana_client_test.dart
- test/solana_wallet_test.dart
> fix(hd-wallet): Corrects the derivation method

- README.md
- packages/borsh/README.md
- packages/borsh_annotation/README.md
- packages/borsh_annotation/lib/src/field_annotation.dart
> chore: Add some documentation and a root readme file.

- packages/solana/lib/src/parsed_message/parsed_spl_token_instruction.dart
- packages/solana/lib/src/parsed_message/parsed_spl_token_instruction.freezed.dart
- packages/solana/lib/src/parsed_message/parsed_spl_token_instruction.g.dart
- packages/solana/lib/src/rpc_client/account_info_response.g.dart
- packages/solana/lib/src/rpc_client/balance_response.g.dart
- packages/solana/lib/src/rpc_client/blockhash_response.g.dart
- packages/solana/lib/src/rpc_client/simulate_tx_result.g.dart
- packages/solana/lib/src/spl_token/associated_account.g.dart
- packages/solana/lib/src/spl_token/token_amount.g.dart
> fix: Add missing `mint` value to the SPL tokens transfer info

- packages/jsonrpc_client/lib/src/client_generator.dart
- packages/solana/lib/src/rpc/client.dart
- packages/solana/lib/src/rpc/client.rpc.dart
- packages/solana/lib/src/rpc/json_rpc_client.dart
- packages/solana/test/rpc_client_test.dart
> feat: Add RPC client timeout

- .github/workflows/check.yml
- README.md
Run tests on push to master.
1. It will allow to catch some subtle errors with merging.
2. It will upload correct reports to code coverage when squashing PR commits.
Also added melos badge.
> chore: Update CI and readme

- packages/solana/lib/src/programs/stake_program/stake_program.dart
> fix: Fix stake instruction parameter

- packages/solana/lib/src/rpc/dto/cluster_node.dart
- packages/solana/lib/src/rpc/dto/cluster_node.g.dart
> fix: Make ClusterNode fields nullable

- packages/cryptoplease/lib/bl/qr_scanner/qr_scanner_bloc.dart
- packages/cryptoplease/lib/bl/qr_scanner/qr_scanner_request.dart
- packages/cryptoplease/lib/bl/qr_scanner/qr_scanner_state.dart
`QrScannerRequest` is now responsible for parsing logic, making `QrScannerBloc` just a coordinator of the logic.
> refactor: Extract parsing logic to QrScannerRequest

- packages/cryptoplease/lib/bl/nft/nft_collection/bloc.dart
- packages/cryptoplease/lib/bl/nft/nft_collection/load_nft_collection.dart
Extracted `loadNftCollection` to a separate method, making `NftCollectionBloc` just an orchestrator of the logic.
> refactor: Extract loadNftCollection

- packages/cryptoplease/lib/bl/outgoing_transfers/outgoing_transfers_bloc/bloc.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/authenticated_flow_screen.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/notifications/components/notification_list.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/outgoing_transfer_flow/split_key_ready_screen.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/send_flow/fungible_token/send_token_flow.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/send_flow/non_fungible_token/send_nft_flow.dart
- Updated activity label for NFT transfer
- Fixed routing for FT and NFT transfers
|1|2|
|-|-|
> fix: NFT update

- .github/dependabot.yaml
> ci: Add dependabot

- packages/cryptoplease_ui/pubspec.yaml
Removed unused dependencies in `cryptoplease_ui`.
> build(cryptoplease_ui): Remove unused dependencies

- packages/cryptoplease/lib/bl/activities/activity.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- packages/cryptoplease/lib/presentation/screens/authenticated/activities/activities_screen.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/activities/components/activity_list.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/home_tabs_screen.dart
- Renamed notifications to activities
- Removed unused l10n keys
> refactor: Clean code

- packages/cryptoplease/lib/presentation/screens/authenticated/send_flow/common/enter_address/enter_address_screen.dart
- packages/cryptoplease/lib/presentation/screens/login/restore_account_screen.dart
- packages/cryptoplease/lib/presentation/utils.dart
`debounce` can behave incorrectly in some corner cases + it's not really needed, so it's removed now.
> fix: Remove debounce

- packages/cryptoplease_ui/lib/src/button.dart
Slightly simplified `CpButton` code.
> refactor: Simplify CpButton

- packages/cryptoplease_ui/lib/cryptoplease_ui.dart
- packages/cryptoplease_ui/lib/src/action_selector/action_selector.dart
- packages/cryptoplease_ui/lib/src/action_selector/button.dart
- packages/cryptoplease_ui/storybook/lib/main.dart
- packages/cryptoplease_ui/storybook/lib/stories/action_selector.dart
Added `CpActionSelector` widget.
> feat(cryptoplease_ui): Add CpActionSelector

- packages/cryptoplease/lib/presentation/components/keypad_key.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/receive_flow/link_request/flow.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/receive_flow/link_request/request_amount_screen.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/receive_flow/link_request/routes.dart
Added stub `RequestAmountScreen` as part of #218 
> feat: Add stub RequestAmountScreen

- packages/cryptoplease/test/bl/transaction_details/transaction_details_bloc_test.dart
- packages/cryptoplease/test/bl/transactions/transactions_bloc_test.dart
- packages/cryptoplease/test/utils.dart
- packages/solana/lib/src/programs/memo_program/memo_instruction.dart
- packages/solana/lib/src/programs/memo_program/memo_program.dart
- packages/solana/lib/src/programs/stake_program/stake_instruction.dart
- packages/solana/lib/src/programs/system_program/system_instruction.dart
- packages/solana/lib/src/programs/token_program/token_instruction.dart
- packages/solana/lib/src/solana_client.dart
- packages/solana/test/anchor_instruction_test.dart
- packages/solana/test/rpc_client_test.dart
- packages/solana/test/spl_token_test.dart
- packages/solana/test/stake_program_test.dart
- packages/solana/test/system_program_test.dart
- packages/solana/test/token_program_test.dart
Followup on #226 to update parameter names and provide more docs.
> refactor!: Update parameters names in instructions

- packages/cryptoplease/lib/bl/outgoing_transfers/outgoing_transfers_bloc/bloc.dart
- packages/cryptoplease/test/bl/split_key_payments/incoming/bloc_test.dart
- packages/cryptoplease/test/bl/transaction_details/transaction_details_bloc_test.dart
- packages/cryptoplease/test/bl/transactions/transactions_bloc_test.dart
- packages/cryptoplease/test/utils.dart
- packages/solana/lib/solana.dart
- packages/solana/lib/src/programs/associated_token_account_program/instruction.dart
- packages/solana/lib/src/programs/associated_token_account_program/program.dart
- packages/solana/lib/src/programs/associated_token_account_program/solana_client_ext.dart
- packages/solana/lib/src/programs/memo_program/instruction.dart
- packages/solana/lib/src/programs/memo_program/program.dart
- packages/solana/lib/src/programs/stake_program/instruction.dart
- packages/solana/lib/src/programs/stake_program/program.dart
- packages/solana/lib/src/programs/system_program/instruction.dart
- packages/solana/lib/src/programs/system_program/program.dart
- packages/solana/lib/src/programs/system_program/solana_client_ext.dart
- packages/solana/lib/src/programs/token_program/instruction.dart
- packages/solana/lib/src/programs/token_program/program.dart
- packages/solana/lib/src/programs/token_program/solana_client_ext.dart
- packages/solana/lib/src/rpc/client.dart
- packages/solana/lib/src/solana_client.dart
- packages/solana/test/airdrop.dart
- packages/solana/test/programs/stake_program/stake_program_test.dart
- packages/solana/test/programs/token_program/token_program_test.dart
- packages/solana/test/system_program_test.dart
Restructure `SolanaClient` to group operations, re-organized imports.
> refactor: Restructure SolanaClient

- packages/cryptoplease/lib/presentation/format_amount.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/outgoing_transfer_flow/split_key_ready_screen.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/receive_flow/link_details/share_link.dart
Display fiat amount in payment request message:
> fix: Show fiat amount in payment request message

- packages/cryptoplease/lib/bl/outgoing_transfers/pending_request_bloc/pending_request_bloc.dart
- packages/cryptoplease/lib/bl/payment_requests/create_payment_request/bloc.dart
- packages/cryptoplease/lib/bl/payment_requests/payment_request.dart
- packages/cryptoplease/lib/bl/split_key_payments/models.dart
- packages/cryptoplease/test/bl/outgoing_transfers/pending_request_bloc/pending_request_bloc_test.dart
Switched to cryptoplease protocol for Solana Pay requests.
> feat: Update solana pay links format

- packages/cryptoplease/lib/presentation/screens/authenticated/flow.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/routes.dart
Added processing for initial pending payment request.
> fix: Process initial pending request

- packages/cryptoplease/lib/bl/payment_requests/repository.dart
- packages/cryptoplease/lib/data/db/payment_request_repository.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/profile/component/danger_section.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/profile/component/profile_section.dart
Clear payment requests when the user logs out.
> fix: Clear payment requests on log out

- packages/cryptoplease/analysis_options.yaml
- packages/cryptoplease/lib/config.dart
- packages/cryptoplease/pubspec.lock
> build: Update configs

- packages/solana/lib/src/constants.dart
- packages/solana/lib/src/encoder/compact_u16.dart
- packages/solana/lib/src/encoder/compiled_message.dart
- packages/solana/lib/src/encoder/compiled_message.freezed.dart
- packages/solana/lib/src/encoder/message.dart
- packages/solana/test/encoder/compact_u16_test.dart
- packages/solana/test/encoder/compiled_message_test.dart
Added `fromSignedTransaction` factory method to `CompiledMessage`.
BREAKING CHANGE: `requiredSignatureCount` is now a getter instead of a construction parameter.
> feat!: Add CompiledMessage.fromSignedTransaction

- packages/cryptoplease/lib/l10n/app_en.arb
> fix: change share text for request payment

- packages/cryptoplease/lib/config.dart
> refactor: Update API URL config

- packages/solana/lib/src/rpc/client.dart
- packages/solana/lib/src/rpc/client.rpc.dart
- packages/solana/lib/src/rpc/dto/dto.dart
- packages/solana/lib/src/rpc/dto/token_largest_account.dart
- packages/solana/lib/src/rpc/dto/token_largest_account.g.dart
- packages/solana/test/rpc_client_test.dart
Updated `getTokenLargestAccounts` response format.
Fixes #269 
> fix: getTokenLargestAccounts response

- packages/solana/lib/src/encoder/compact_u16.dart
- packages/solana/lib/src/encoder/instruction.dart
- packages/solana/lib/src/encoder/message.dart
- packages/solana/lib/src/encoder/message_header.dart
- packages/solana/test/encoder/message_test.dart
> feat: Add Message.decompile

- packages/borsh/CHANGELOG.md
- packages/borsh/pubspec.yaml
- packages/borsh/test/structs.dart
- packages/borsh/test/structs.g.dart
- packages/borsh/test/structs_test.dart
- packages/borsh_annotation/CHANGELOG.md
- packages/borsh_annotation/lib/src/binary_reader.dart
- packages/borsh_annotation/lib/src/binary_writer.dart
- packages/borsh_annotation/pubspec.yaml
- packages/solana/CHANGELOG.md
- packages/solana/lib/src/encoder/byte_array.dart
- packages/solana/pubspec.yaml
Fixed u64 serialization/deserialization
Fixes #280 
> chore: Fix borsh to work in JS

- packages/cryptoplease_link/public/solana-pay-styles.css
- packages/cryptoplease_link/templates/solana-pay.html
- Changes web layout style;
- Changes mobile layout style.
<details><summary>Mobile</summary>
</details>
<details><summary>Web</summary>
</details>
> feat: improve solana pay webpage

- packages/cryptoplease/lib/bl/swap_tokens/selector/swap_selector_bloc.dart
- packages/cryptoplease/lib/presentation/screens/authenticated/swap_tokens/screens/swap_token_selector_screen.dart
> fix: sort token list in swap flow

- packages/cryptoplease/lib/app/screens/dynamic_links/dynamic_links_controller.dart
- packages/cryptoplease/lib/core/analytics/analytics_manager.dart
- packages/cryptoplease/lib/features/swap_tokens/bl/selector/swap_selector_bloc.dart
- packages/cryptoplease/lib/features/swap_tokens/presentation/screens/swap_token_order_screen.dart
Add analytics event for swap transaction created.
> feat: Add analytics for swap

- packages/cryptoplease/lib/app/screens/authenticated/flow.dart
- packages/cryptoplease/lib/features/outgoing_transfer/presentation/outgoing_transfer_flow/outgoing_transfer_flow.dart
- packages/cryptoplease/lib/features/outgoing_transfer/presentation/send_flow/fungible_token/send_flow.dart
- packages/cryptoplease/lib/features/outgoing_transfer/presentation/send_flow/non_fungible_token/send_flow.dart
- packages/cryptoplease/lib/features/pending_request/presentation/pending_request_listener.dart
Fix navigation stack clearing.
Fixes #324 
> fix: properly clear navigation stack after creating link

- packages/cryptoplease/CHANGELOG.md
- packages/cryptoplease/lib/features/outgoing_transfer/bl/get_first_link.dart
- packages/cryptoplease/pubspec.yaml
- packages/cryptoplease_link/public/solana-shareable-styles.css
- packages/cryptoplease_link/templates/solana-shareable.html
Switch to Firebase-based links
> feat: switch to Firebase links

- packages/cryptoplease/lib/app/screens/authenticated/home_tabs_screen.dart
> feat: remove NFT tab

- packages/solana/test/programs/associated_token_account_program/program_test.dart
Added new test for ATA program.
> test: Add ATA test

- packages/cryptoplease/lib/features/transactions/bl/details/transaction_details_bloc.dart
- packages/cryptoplease/lib/features/transactions/bl/list/transactions_bloc.dart
- packages/cryptoplease_link/bin/server.dart
- packages/cryptoplease_link/lib/src/constants.dart
- packages/cryptoplease_link/lib/src/payments/create_payment.dart
- packages/cryptoplease_link/lib/src/payments/dto.dart
- packages/cryptoplease_link/lib/src/payments/dto.freezed.dart
- packages/cryptoplease_link/lib/src/payments/dto.g.dart
- packages/cryptoplease_link/lib/src/payments/escrow_account.dart
- packages/cryptoplease_link/lib/src/payments/escrow_account.freezed.dart
- packages/cryptoplease_link/lib/src/payments/handler.dart
- packages/cryptoplease_link/lib/src/payments/receive_payment.dart
- packages/cryptoplease_link/pubspec.lock
- packages/cryptoplease_link/pubspec.yaml
- packages/cryptoplease_link/tests/config.dart
- packages/cryptoplease_link/tests/payments/create_payment_test.dart
- packages/cryptoplease_link/tests/payments/escrow_account_test.dart
- packages/cryptoplease_link/tests/payments/receive_payment_test.dart
- packages/cryptoplease_link/tests/payments/utils.dart
- packages/solana/CHANGELOG.md
- packages/solana/lib/src/crypto/crypto.dart
- packages/solana/lib/src/rpc/dto/account_data/account_data.dart
- packages/solana/lib/src/rpc/dto/block.g.dart
- packages/solana/lib/src/rpc/dto/parse_with_encoding.dart
- packages/solana/lib/src/rpc/dto/transaction.dart
- packages/solana/lib/src/rpc/dto/transaction.g.dart
- packages/solana/lib/src/rpc/dto/transaction_details.g.dart
- packages/solana/lib/src/solana_pay/solana_client_ext.dart
- packages/solana/pubspec.yaml
- packages/solana/test/solana_client_test.dart
> feat: Add server-generated tx

- packages/cryptoplease/lib/features/profile/components/menu_button.dart
> fix: chevron color in menu

- packages/cryptoplease/lib/features/profile/components/menu_header.dart
fix: change size of button in menu
> fix: change size of button in menu

- README.md
- packages/cryptoplease/lib/app/components/keypad_key.dart
> fix: font-size for numeric pad is 24

- packages/cryptoplease/lib/features/profile/components/menu_header.dart
- Remove the stablecoin selector and put USDC as default on the menu page
<details>
<summary>Preview</summary>
</details>
Fixes #345 
> feat: remove stablecoin selector, set usdc as default token

- packages/cryptoplease/lib/app/screens/authenticated/home_tabs_screen.dart
- Change bottom menu arrangement
<details>
<summary>Preview</summary>
</details>
Fixes #345 
> feat: change bottom menu arrangement

- packages/cryptoplease/lib/features/request_pay/presentation/request_pay_flow.dart
- packages/cryptoplease/lib/features/request_pay/presentation/screens/request_pay_screen.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- Don't disable button Request and Pay even if you have $0
<details>
<summary>Preview</summary>
https://user-images.githubusercontent.com/19499575/183454706-d36e1b74-83b5-4bc5-812c-d81754d74535.mp4
</details>
Fixes #345 
> feat: keep request and pay buttons enabled

- packages/cryptoplease/README.md
Fixed a minor grammatical mistake in the readme.md file.
> docs: updated readme

- packages/cryptoplease/lib/app/screens/authenticated/routes.dart
- Menu as first page when app starts
> fix: menu page when startup

- packages/jsonrpc_client/pubspec.yaml
> build: Update dependencies

- packages/cryptoplease/android/build.gradle
- packages/cryptoplease/android/gradle/wrapper/gradle-wrapper.properties
> build: bump gradle version

- packages/solana/lib/src/exceptions/json_rpc_exception.dart
- packages/solana/lib/src/exceptions/json_rpc_exception.g.dart
- packages/solana/test/exceptions/json_rpc_exception_test.dart
Added `TransactionError` enum and `JsonRpcException.transactionError` getter.
> feat: add TransactionError

- packages/cryptoplease/lib/app/components/refresh_balance_wrapper.dart
- packages/cryptoplease/lib/app/screens/authenticated/wallet_screen.dart
- packages/cryptoplease/lib/features/profile/menu_screen.dart
- Adds balance refresh logic to menu screen
- Reuse refresh balance logic
> fix: add balance refresh on menu screen, reuse refresh logic

- packages/solana/lib/src/encoder/signed_tx.dart
- packages/solana/lib/src/rpc/client.dart
- packages/solana/lib/src/rpc/extension.dart
> feat: Add solana helper methods

- packages/cryptoplease/lib/features/incoming_split_key_payment/bl/bloc.dart
- packages/cryptoplease/lib/features/incoming_split_key_payment/bl/event.dart
- packages/cryptoplease/lib/features/incoming_split_key_payment/bl/state.dart
- packages/cryptoplease/lib/features/incoming_split_key_payment/bl/tx_processor.dart
- packages/cryptoplease/lib/features/incoming_split_key_payment/module.dart
- packages/cryptoplease/lib/features/incoming_split_key_payment/presentation/components/second_part_ready_content.dart
- packages/cryptoplease/test/features/incoming_split_key_payment/bloc_test.dart
Update the flow for receiving incoming payment.
Fixes #326 
> fix: recover from error on incoming payment

- .github/workflows/check_pr.yml
- Makefile
- packages/cryptoplease/Makefile
- packages/cryptoplease/lib/core/tokens/token_list.dart
- packages/cryptoplease/test/core/balances/balances_bloc_test.dart
- packages/cryptoplease/test/features/incoming_split_key_payment/bloc_test.dart
- packages/cryptoplease/test/features/transactions/transaction_details_bloc_test.dart
- packages/cryptoplease/test/features/transactions/transactions_bloc_test.dart
- packages/cryptoplease/test/utils.dart
- packages/cryptoplease/tool/tests_setup.dart
> test: optimize tests

- packages/cryptoplease/lib/app/screens/authenticated/components/header_buttons.dart
- packages/cryptoplease/lib/config.dart
- packages/cryptoplease/lib/features/add_funds/bl/add_funds_bloc.dart
- packages/cryptoplease/lib/features/add_funds/data/sign_funds_client.dart
- packages/cryptoplease/lib/features/add_funds/data/sign_funds_request.dart
- packages/cryptoplease/lib/features/add_funds/presentation/add_funds_screen.dart
- packages/cryptoplease/lib/features/profile/components/menu_header.dart
- packages/cryptoplease/pubspec.lock
- packages/cryptoplease/pubspec.yaml
- packages/cryptoplease/test/features/add_funds/add_funds_bloc_test.dart
- packages/cryptoplease_link/bin/server.dart
- packages/cryptoplease_link/lib/src/constants.dart
- packages/cryptoplease_link/lib/src/handlers/moonpay_handler.dart
- packages/cryptoplease_link/lib/src/moonpay/handler.dart
- packages/cryptoplease_link/pubspec.lock
- packages/cryptoplease_link/pubspec.yaml
- Allow buy USDC or SOL via MoonPay;
- Add MoonPay handler on cryptoplease_link project.
> feat: moonpay sign logic on cryptoplease_link, allow buy usdc

- packages/sms_wallet/android/src/main/java/com/solana/sms_wallet/Api.java
- packages/sms_wallet/android/src/main/kotlin/com/solana/sms_wallet/ScenarioProxy.kt
- packages/sms_wallet/example/lib/mobile_wallet/bloc.dart
- packages/sms_wallet/lib/sms_wallet.dart
- packages/sms_wallet/lib/src/api.dart
- packages/sms_wallet/lib/src/requests/reauthorize.dart
- packages/sms_wallet/lib/src/requests/reauthorize.freezed.dart
- packages/sms_wallet/lib/src/scenario.dart
- packages/sms_wallet/pigeons/api.dart
Added `reauthorize` request support.
> feat: Add reauthorize request

- .github/workflows/e2e_tests.yml
- packages/cryptoplease/integration_test/app_test.dart
- Updated the expected string to match with the actual button string.
- Updated e2e tests script
Fixes #373
> fix: update failing e2e test

- packages/cryptoplease/lib/features/swap_tokens/bl/transaction/swap_transaction_bloc.dart
- packages/solana/lib/src/crypto/ed25519_hd_keypair.dart
- packages/solana/lib/src/encoder/compiled_message.dart
- packages/solana/lib/src/encoder/message.dart
- packages/solana/lib/src/encoder/signed_tx.dart
- packages/solana/test/encoder/message_test.dart
- packages/solana/test/encoder/signed_tx_test.dart
Added `SignedTx.decode` method.
> feat: add SignedTx.decode

- packages/cryptoplease/lib/features/swap_tokens/bl/selector/swap_selector_bloc.dart
- Used isolates on expensive functions related to mapping tokens
Fixes #315
> fix: fixed jank on swap page  

- packages/borsh/pubspec.yaml
- packages/borsh_annotation/pubspec.yaml
- packages/cryptoplease/pubspec.lock
- packages/cryptoplease/pubspec.yaml
- packages/cryptoplease_link/cryptoplease_api/pubspec.yaml
- packages/cryptoplease_link/pubspec.lock
- packages/cryptoplease_link/pubspec.yaml
- packages/cryptoplease_ui/pubspec.yaml
- packages/cryptoplease_ui/storybook/pubspec.lock
- packages/cryptoplease_ui/storybook/pubspec.yaml
- packages/jsonrpc_client/pubspec.yaml
- packages/solana/pubspec.yaml
- packages/solana_mobile_client/example/pubspec.lock
- packages/solana_mobile_client/example/pubspec.yaml
- packages/solana_mobile_client/pubspec.yaml
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_mobile_wallet/example/pubspec.yaml
- packages/solana_mobile_wallet/pubspec.yaml
Updated `mews_pedantic` version.
> build: update mews_pedantic

- packages/solana_mobile_client/android/src/main/java/com/solana/solana_mobile_client/Api.java
- packages/solana_mobile_client/android/src/main/kotlin/com/solana/solana_mobile_client/ApiLocalAssociationScenario.kt
- packages/solana_mobile_client/example/lib/client.dart
- packages/solana_mobile_client/example/lib/client.freezed.dart
- packages/solana_mobile_client/example/lib/main.dart
- packages/solana_mobile_client/lib/src/api.dart
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.dart
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.freezed.dart
- packages/solana_mobile_client/pigeons/api.dart
Added authorization methods: authorize, reauthorize, deauthorize.
> feat: add authorization methods

- packages/solana_mobile_client/android/src/main/java/com/solana/solana_mobile_client/Api.java
- packages/solana_mobile_client/android/src/main/kotlin/com/solana/solana_mobile_client/ApiLocalAssociationScenario.kt
- packages/solana_mobile_client/example/lib/client.dart
- packages/solana_mobile_client/example/lib/client.freezed.dart
- packages/solana_mobile_client/example/lib/main.dart
- packages/solana_mobile_client/lib/src/api.dart
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.dart
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.freezed.dart
- packages/solana_mobile_client/pigeons/api.dart
Added `requestAirdrop` and `signTransactions` methods.
> feat: add client methods

- packages/cryptoplease/lib/core/tx_sender.dart
- packages/cryptoplease/test/core/tx_sender_test.dart
- packages/solana/lib/solana.dart
Added `TxSender` service as a helper for update tx handling.
> feat: create TxSender

- packages/cryptoplease/lib/core/resign_tx.dart
- packages/cryptoplease/lib/core/split_key_payments/transaction/creators/cp_tx_creator.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/bl/bloc.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/bloc.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/link_shortener.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/outgoing_split_key_payment.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/repository.dart
- packages/cryptoplease/pubspec.lock
- packages/cryptoplease/pubspec.yaml
Added new model and bloc for outgoing split-key transfer functionality.
> feat: add new outgoing transfer

- packages/cryptoplease/lib/features/incoming_split_key_payments/bl/bloc.dart
- packages/cryptoplease/lib/features/incoming_split_key_payments/bl/incoming_split_key_payment.dart
- packages/cryptoplease/lib/features/incoming_split_key_payments/bl/repository.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/bloc.dart
Added new `IncomingSplitKeyPayment` model and the corresponding bloc.
> feat: add new incoming split-key model and bloc

- packages/cryptoplease/lib/app/screens/authenticated/flow.dart
- packages/cryptoplease/lib/app/screens/authenticated/routes.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/bloc.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/outgoing_split_key_payment.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/repository.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/data/repository.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/presentation/oskp_screen.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/presentation/routes.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/presentation/share_links_screen.dart
- packages/cryptoplease/lib/features/request_pay/presentation/request_pay_flow.dart
- packages/cryptoplease/lib/features/request_pay/presentation/routes.dart
- packages/cryptoplease/lib/features/request_pay/presentation/screens/split_key_confirm_screen/components/token_create_link_content.dart
- packages/cryptoplease/lib/features/request_pay/presentation/screens/split_key_confirm_screen/split_key_confirm_screen.dart
- packages/cryptoplease/pubspec.lock
- packages/cryptoplease_ui/lib/src/status_screen.dart
Outgoing split key payments are now connected to the UI.
> feat: update OSKP

- packages/cryptoplease/lib/app/components/token_fiat_input_widget/enter_amount_keypad.dart
- packages/cryptoplease/lib/app/screens/authenticated/flow.dart
- packages/cryptoplease/lib/app/screens/dynamic_links/dynamic_links_controller.dart
- packages/cryptoplease/lib/app/screens/dynamic_links/dynamic_links_notifier.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/presentation/link_listener.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/presentation/routes.dart
- packages/cryptoplease/lib/features/request_pay/presentation/request_pay_flow.dart
- packages/cryptoplease/lib/features/request_pay/presentation/screens/direct_pay_screen.dart
- packages/cryptoplease/lib/main.dart
Incoming payment requests – Solana Pay and custom ones – use new models now.
> feat: use new models in incoming payment requests

- packages/cryptoplease/lib/data/db/db.dart
- packages/cryptoplease/lib/features/payment_request/bl/repository.dart
- packages/cryptoplease/lib/features/pending_activities/pending_activities_repository.dart
> refactor: move payment request table data

- packages/cryptoplease/lib/l10n/app_en.arb
> refactor: remove unused l10n strings

- packages/cryptoplease/assets/icons/oskp_activity_sent.svg
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/repository.dart
- packages/cryptoplease/lib/features/pending_activities/components/oksp_tile.dart
- packages/cryptoplease/lib/features/pending_activities/components/payment_request_tile.dart
- packages/cryptoplease/lib/features/pending_activities/components/pending_activities_list.dart
- packages/cryptoplease/lib/features/pending_activities/components/styles.dart
- packages/cryptoplease/lib/features/pending_activities/pending_activities_repository.dart
- packages/cryptoplease/lib/features/pending_activities/pending_activity.dart
> feat: update OSKPTile in activity

- packages/cryptoplease/lib/app/components/decorated_window.dart
- packages/cryptoplease/lib/app/screens/authenticated/activities/activities_screen.dart
- packages/cryptoplease/lib/app/screens/authenticated/investments/components/wallet_tab_bar.dart
- packages/cryptoplease/lib/app/screens/authenticated/profile/components/menu_header.dart
- packages/cryptoplease/lib/app/screens/authenticated/receive_flow/share_address_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/backup_phrase_flow/backup_confirm_phrase_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/puzzle_reminder/components/puzzle_screen.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/presentation/oskp_confirmation_screen.dart
- packages/cryptoplease/lib/features/payment_request/presentation/link_request/payer_name_screen.dart
- packages/cryptoplease/lib/features/pending_activities/components/pending_activities_list.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- packages/cryptoplease_ui/lib/cryptoplease_ui.dart
- packages/cryptoplease_ui/lib/src/action_selector/action_selector.dart
- packages/cryptoplease_ui/lib/src/app_bar.dart
- packages/cryptoplease_ui/lib/src/status_screen.dart
- packages/cryptoplease_ui/lib/src/tab_bar.dart
- packages/cryptoplease_ui/storybook/lib/stories/app_bar.dart
> feat: add tabbar to activity screen

- packages/cryptoplease/lib/app/components/share_message/header.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/presentation/share_links_screen.dart
- packages/cryptoplease/lib/features/payment_request/presentation/link_details/share_link.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- Fixes share payment request text
Fixes #533 
> fix: share payment request copy

- packages/cryptoplease/lib/app/screens/authenticated/activities/activities_screen.dart
- packages/cryptoplease/lib/features/pending_activities/components/pending_activities_list.dart
Added "Coming soon!" label for transactions tab.
> feat: coming soon label for transactions

- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/oskp_verifier.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/bl/repository.dart
- packages/cryptoplease/lib/features/pending_activities/components/pending_activities_list.dart
Added `OSKPVerifier` to listen for the OSKP completion.
> feat: add oskp verifier

- packages/cryptoplease/lib/config.dart
- Change Help URL
https://user-images.githubusercontent.com/19499575/197780338-af04b3a0-430e-4f4d-8d76-234bae19aabc.mov
Fixes #557 
> feat: change help center url

- packages/cryptoplease/lib/app/screens/authenticated/profile/components/menu_section.dart
- packages/cryptoplease/lib/app/screens/authenticated/profile/menu_screen.dart
- packages/cryptoplease/lib/core/presentation/format_date.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/presentation/oskp_screen.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- Fixed scrolling and simplified layout.
- Updated date formatting: added "Today".
- Added amount to "Creating links" timeline item.
> feat: small improvements

- packages/cryptoplease/README.md
- packages/cryptoplease/android/app/src/main/AndroidManifest.xml
- packages/cryptoplease/ios/Runner/Info.plist
- packages/cryptoplease/lib/app/app.dart
- packages/cryptoplease/lib/storybook/stories/app/app_wrapper.dart
- packages/cryptoplease/lib/storybook/stories/app_bar.dart
- packages/cryptoplease/lib/storybook/stories/background_gradient.dart
- packages/cryptoplease/lib/storybook/stories/bottom_button.dart
- packages/cryptoplease/lib/storybook/stories/bullet_item.dart
- packages/cryptoplease/lib/storybook/stories/chip.dart
- packages/cryptoplease/lib/storybook/stories/loader.dart
Changed app name to "Espresso Cash".
> feat: update app name

- packages/cryptoplease/lib/app/screens/authenticated/cash_out/cash_out_screen.dart
- packages/cryptoplease/lib/config.dart
- packages/cryptoplease/lib/features/add_funds/bl/add_funds_bloc.dart
- Updated FTX add cash and cash out urls
> feat: update ftx support urls

- packages/cryptoplease/lib/features/payment_request/bl/create_payment_request/bloc.dart
- packages/cryptoplease/lib/features/payment_request/bl/create_payment_request/event.dart
- packages/cryptoplease/lib/features/payment_request/bl/create_payment_request/state.dart
- packages/cryptoplease/lib/features/payment_request/bl/payment_request.dart
- packages/cryptoplease/lib/features/payment_request/bl/repository.dart
- packages/cryptoplease/lib/features/payment_request/presentation/link_details/flow.dart
- packages/cryptoplease/lib/features/payment_request/presentation/link_details/tx_result_screen.dart
- packages/cryptoplease/lib/features/payment_request/presentation/link_request/flow.dart
- packages/cryptoplease/lib/features/pending_activities/components/payment_request_tile.dart
- packages/cryptoplease/lib/l10n/app_en.arb
Updated naming in payment request module.
> refactor: update payment request naming

- packages/cryptoplease/lib/app/screens/authenticated/profile/menu_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/backup_phrase_flow/backup_warning_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/routes.dart
> refactor: update backup phrase routes

- packages/cryptoplease/lib/features/backup_phrase/presentation/backup_phrase_flow/backup_confirm_phrase_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/backup_phrase_flow/backup_phrase_flow_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/backup_phrase_flow/backup_phrase_screen.dart
- packages/cryptoplease/lib/features/backup_phrase/presentation/backup_phrase_flow/backup_warning_screen.dart
Fixed routing for backup phrase flow.
> fix: backup flow routing

- README.md
- packages/cryptoplease/README.md
- packages/cryptoplease/lib/config.dart
- packages/solana/README.md
Updated twitter URLs in the app and in docs.
> feat: Twitter urls

- packages/cryptoplease/lib/config.dart
fix: add https for ftx url
Fixes #___
> fix: add https for ftx url

- packages/cryptoplease/lib/features/ramp/src/bl/repository.dart
- packages/cryptoplease_link/lib/src/moonpay/handler.dart
- Changes USDC Token symbol to match MoonPay currency.
> fix: changes usdc token symbol when requesting funds

- packages/cryptoplease/lib/app/screens/authenticated/wallet_flow/wallet_flow_screen.dart
- packages/cryptoplease/lib/app/screens/authenticated/wallet_flow/wallet_main_screen.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- packages/cryptoplease/lib/ui/amount_with_equivalent.dart
- packages/cryptoplease/lib/ui/chip.dart
- packages/cryptoplease/lib/ui/colors.dart
- packages/cryptoplease/lib/ui/shake.dart
Added animated error to the wallet flow:
https://user-images.githubusercontent.com/853356/199303081-5964a141-1804-4beb-93e8-6b8e58187fa5.mp4
> feat: add animated error to wallet flow

- packages/cryptoplease/lib/app/screens/authenticated/profile/profile_screen.dart
- packages/cryptoplease/lib/app/screens/authenticated/wallet_flow/wallet_flow_screen.dart
- packages/cryptoplease/lib/core/async_snapshot.dart
- packages/cryptoplease/lib/core/fee_label.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/src/bl/fee.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/src/presentation/link_listener.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/src/presentation/odp_confirmation_screen.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/src/presentation/oskp_confirmation_screen.dart
- packages/cryptoplease/lib/features/qr_scanner/src/qr_address_data.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- packages/cryptoplease/test/features/qr_scanner/qr_scanner_bloc_test.dart
- packages/cryptoplease_link/cryptoplease_api/lib/cryptoplease_api.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/client.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/client.g.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/get_fees.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/get_fees.freezed.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/get_fees.g.dart
- packages/cryptoplease_link/lib/src/payments/handler.dart
- packages/cryptoplease_link/lib/src/utils.dart
Added label to confirmation screens:
| Direct payment | Shareable links |
| --- | --- |
| ![](https://user-images.githubusercontent.com/853356/199332848-b36fd828-8f54-4c74-8340-468e9466c1d0.png) | ![](https://user-images.githubusercontent.com/853356/199314866-53eec04f-fb98-40a3-9b4e-c1f451aa81af.png) |
> feat: add fee label

- packages/cryptoplease/lib/l10n/app_en.arb
> fix: update successful payment label

- .github/workflows/check_pr.yml
- packages/solana/lib/src/anchor/instruction.dart
- packages/solana/lib/src/metaplex/instructions/create_metadata_account.dart
- packages/solana/lib/src/metaplex/instructions/create_metadata_account.g.dart
- packages/solana/lib/src/metaplex/instructions/fixed_string.dart
- packages/solana/lib/src/metaplex/instructions/instructions.dart
- packages/solana/lib/src/metaplex/metadata.dart
- packages/solana/lib/src/metaplex/metaplex.dart
- packages/solana/lib/src/metaplex/rpc_client_ext.dart
- packages/solana/lib/src/metaplex/utils.dart
- packages/solana/test/config.dart
- packages/solana/test/metaplex/instructions/create_metadata_account_test.dart
Added support for `CreateMetadataAccountV3`.
Fixes #591
> feat: add metaplex CreateMetadataAccountV3

- packages/cryptoplease/lib/app/screens/authenticated/wallet_flow/wallet_flow_screen.dart
- packages/cryptoplease/lib/features/qr_scanner/src/qr_scanner_request.dart
> fix: take reference into account when scanning QR code

- packages/solana/lib/src/rpc/extension.dart
> feat: add parameters to getTransactionsList

- packages/solana/lib/src/rpc/extension.dart
> fix: getTransactionsList for empty list

- packages/cryptoplease/ios/Podfile.lock
- packages/cryptoplease/lib/app/screens/authenticated/activities/activities_screen.dart
- packages/cryptoplease/lib/app/screens/authenticated/profile/components/profile_section.dart
- packages/cryptoplease/lib/app/screens/authenticated/profile/components/version_section.dart
- packages/cryptoplease/lib/core/feature_flags.dart
- packages/cryptoplease/lib/main.dart
- packages/cryptoplease/pubspec.lock
- packages/cryptoplease/pubspec.yaml
Added feature flags functionality and hid activities tab behind FF.
> feat: hide transactions tab behind FF

- packages/cryptoplease/lib/core/feature_flags.dart
- packages/cryptoplease/lib/features/app_lock/src/presentation/app_lock_settings.dart
- packages/cryptoplease/lib/storybook/stories/switch.dart
- packages/cryptoplease/lib/ui/switch.dart
- Updates CpSwitch with new color
- Fixes issue when running storybook
> feat: update CpSwitch design

- packages/cryptoplease/lib/app/app.dart
- packages/cryptoplease/lib/core/analytics/analytics_manager.dart
- packages/cryptoplease/lib/features/incoming_split_key_payments/src/presentation/first_part_ready_screen.dart
- packages/cryptoplease/lib/features/incoming_split_key_payments/src/presentation/pending_iskp_listener.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/module.dart
- Added route observer analytics
- Added analytics event during links creation and links received
Fixes #620
> feat: update analytics

- packages/cryptoplease/lib/core/transactions/tx_sender.dart
Fixes the situation when there was an error after sending tx but before waiting, and during the next attempt, blockhash was already expired. Added check if the tx was still submitted.
> fix: check if tx with expired bh already submitted

- packages/cryptoplease_link/jupiter_aggregator/lib/src/client.dart
- packages/cryptoplease_link/jupiter_aggregator/lib/src/client.g.dart
- packages/cryptoplease_link/jupiter_aggregator/lib/src/model.dart
- packages/cryptoplease_link/jupiter_aggregator/lib/src/model.freezed.dart
- packages/cryptoplease_link/jupiter_aggregator/lib/src/model.g.dart
- Adds Jupiter Price Client to `jupiter_aggregator` package
Breakdown of #632 
> feat: add jupiter price client

- packages/solana_mobile_wallet/android/build.gradle
- packages/solana_mobile_wallet/android/src/main/java/com/solana/solana_mobile_wallet/Api.java
- packages/solana_mobile_wallet/android/src/main/kotlin/com/solana/solana_mobile_wallet/ScenarioProxy.kt
- packages/solana_mobile_wallet/android/src/main/kotlin/com/solana/solana_mobile_wallet/SolanaMobileWalletPlugin.kt
- packages/solana_mobile_wallet/example/lib/main.dart
- packages/solana_mobile_wallet/example/lib/mobile_wallet/bloc.dart
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_mobile_wallet/example/pubspec.yaml
- packages/solana_mobile_wallet/lib/src/api.dart
- packages/solana_mobile_wallet/lib/src/requests/sign_and_send_transactions.dart
- packages/solana_mobile_wallet/lib/src/requests/sign_and_send_transactions.freezed.dart
- packages/solana_mobile_wallet/lib/src/scenario.dart
- packages/solana_mobile_wallet/lib/src/wallet_config.dart
- packages/solana_mobile_wallet/lib/src/wallet_config.freezed.dart
- packages/solana_mobile_wallet/lib/src/wallet_config.g.dart
- packages/solana_mobile_wallet/pigeons/api.dart
Updated SDK to 1.0.0, added missing methods implementation.
> feat: Mobile wallet updates

- packages/solana_mobile_client/android/build.gradle
- packages/solana_mobile_client/android/src/main/java/com/solana/solana_mobile_client/Api.java
- packages/solana_mobile_client/android/src/main/kotlin/com/solana/solana_mobile_client/ApiLocalAssociationScenario.kt
- packages/solana_mobile_client/lib/src/api.dart
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.dart
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.freezed.dart
- packages/solana_mobile_client/pigeons/api.dart
Updated native library to 1.0.0, added missing methods.
> feat: update library to 1.0.0

- packages/cryptoplease_link/lib/src/constants.dart
- packages/cryptoplease_link/lib/src/swap/create_swap.dart
> feat: add minimum swap fee

- packages/cryptoplease_link/bin/server.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/client.dart
- packages/cryptoplease_link/lib/src/constants.dart
- packages/cryptoplease_link/lib/src/swap/create_swap.dart
- packages/cryptoplease_link/lib/src/swap/jupiter_repository.dart
- packages/cryptoplease_link/pubspec.lock
- packages/cryptoplease_link/pubspec.yaml
> feat: update fees calculation

- packages/solana/test/anchor_tutorial_types/basic1.dart
- packages/solana/test/anchor_tutorial_types/basic1.g.dart
Generate code for discriminator to get offset shifted correctly.
Discriminator field was copied manually, but no manual offset was provided to the reader. 
> test: generate code for discriminator in test/tutorial.

- packages/cryptoplease/lib/features/incoming_tip_payments/module.dart
- packages/cryptoplease/lib/features/outgoing_tip_payments/module.dart
- Clears outgoing and incoming tip db entries on logout
> fix: clear tip db on logout

- packages/cryptoplease/lib/features/incoming_split_key_payments/src/presentation/incoming_split_key_payment_screen.dart
- packages/cryptoplease/lib/features/incoming_tip_payments/src/presentation/incoming_tip_screen.dart
- packages/cryptoplease/lib/features/outgoing_direct_payments/src/presentation/odp_details_screen.dart
- packages/cryptoplease/lib/features/outgoing_split_key_payments/src/presentation/oskp_screen.dart
- packages/cryptoplease/lib/features/outgoing_tip_payments/src/presentation/ot_screen.dart
- packages/cryptoplease/lib/features/swap/src/swap/process_swap_screen.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- packages/cryptoplease/lib/ui/transfer_status/transfer_error.dart
- packages/cryptoplease/lib/ui/transfer_status/transfer_success.dart
- Updated incoming success content
> fix: update incoming transfer success message

- packages/cryptoplease/lib/app/screens/authenticated/investments/components/total_balance_widget.dart
- packages/cryptoplease/lib/core/balances/presentation/watch_balance.dart
- packages/cryptoplease/lib/features/investments/widgets/my_portfolio.dart
- remove usdc from crypto section
> fix: investment screen fixes

- packages/cryptoplease/lib/features/investments/widgets/crypto_investments.dart
- packages/cryptoplease/lib/features/investments/widgets/portfolio_widget.dart
Fixed update for investments widget.
> fix: investments sync

- packages/cryptoplease/lib/app/screens/authenticated/activities/activities_screen.dart
- packages/cryptoplease/lib/app/screens/authenticated/home_screen.dart
- packages/cryptoplease/lib/app/screens/authenticated/investments/investments_screen.dart
- packages/cryptoplease/lib/core/presentation/page_fade_wrapper.dart
- packages/cryptoplease/lib/features/token_chart/widgets/token_chart.dart
- updated token chart tooltip to be one line
- added space and fade above nav bar on Investment and Activities screen
> fix: minor ui updates

- packages/solana_mobile_client/CHANGELOG.md
- packages/solana_mobile_client/pubspec.yaml
- packages/solana_mobile_wallet/CHANGELOG.md
- packages/solana_mobile_wallet/pubspec.yaml
- packages/solana_seed_vault/CHANGELOG.md
- packages/solana_seed_vault/pubspec.yaml
> chore: publish packages

- README.md
- Updates README to include new packages
> docs: update readme to include new packages

- packages/cryptoplease/lib/features/activities/src/transaction_repository.dart
- packages/cryptoplease/lib/features/activities/src/widgets/transaction_item.dart
- Removes duplicate items on transaction list
> fix: duplicate items on transaction list

- packages/cryptoplease/lib/features/investments/widgets/crypto_investments.dart
- hide crypto investments section when empty balance
Fixes #723
> fix: hide crypto investments section if 0 balance

- .github/workflows/check_pr.yml
- Dockerfile
- Makefile
> ci: check dependencies graph

- packages/cryptoplease/pubspec.lock
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/add_funds.freezed.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/create_payment.freezed.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/get_fees.freezed.dart
- packages/cryptoplease_link/cryptoplease_api/lib/src/dto/swap.freezed.dart
- packages/cryptoplease_link/jupiter_aggregator/lib/src/model.freezed.dart
- packages/cryptoplease_link/lib/src/app.freezed.dart
- packages/cryptoplease_link/lib/src/payments/create_direct_payment.freezed.dart
- packages/cryptoplease_link/lib/src/payments/escrow_account.freezed.dart
- packages/cryptoplease_link/lib/src/swap/create_swap.freezed.dart
- packages/cryptoplease_link/lib/src/swap/jupiter_repository.freezed.dart
- packages/cryptoplease_link/pubspec.lock
- packages/solana_mobile_client/example/lib/client.freezed.dart
- packages/solana_mobile_client/example/pubspec.lock
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.freezed.dart
- packages/solana_mobile_wallet/example/lib/mobile_wallet/bloc.freezed.dart
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_mobile_wallet/lib/src/auth_issuer_config.freezed.dart
- packages/solana_mobile_wallet/lib/src/requests/authorize.freezed.dart
- packages/solana_mobile_wallet/lib/src/requests/reauthorize.freezed.dart
- packages/solana_mobile_wallet/lib/src/requests/sign_and_send_transactions.freezed.dart
- packages/solana_mobile_wallet/lib/src/requests/sign_transactions.freezed.dart
- packages/solana_mobile_wallet/lib/src/wallet_config.freezed.dart
- packages/solana_seed_vault/example/pubspec.lock
Updated generated code after migration to Flutter 3.7.
> refactor: rebuild generated code

- packages/cryptoplease/lib/features/activities/src/transaction_repository.dart
- Updates transaction items whenever their activity changes status.
- Watches the activity instead of reading once from db.
Fixes #736
> fix: watch activities on transaction items

- packages/cryptoplease/lib/features/qr_scanner/src/widgets/qr_scanner_screen.dart
- packages/cryptoplease/pubspec.yaml
- Fix camera permission API on mobile scanner
> fix: migrate camera permission api on qrscreen

- packages/cryptoplease/lib/features/swap/src/swap/process_swap_screen.dart
- packages/cryptoplease/lib/l10n/app_en.arb
- Improves buy and sell success message
</details>
Fixes #752 
> feat: improve buy and sell success message

- .github/workflows/check_pr.yml
- packages/borsh/pubspec.yaml
- packages/borsh_annotation/pubspec.yaml
- packages/espressocash_app/lib/features/favorite_tokens/widgets/favorite_tokens_list.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/db.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/db.dart
- packages/espressocash_app/lib/features/swap/db.dart
- packages/espressocash_app/lib/features/token_chart/widgets/token_chart.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_backend/bin/server.dart
- packages/espressocash_backend/espressocash_api/pubspec.yaml
- packages/espressocash_backend/jupiter_aggregator/pubspec.yaml
- packages/espressocash_backend/lib/src/moonpay/handler.dart
- packages/espressocash_backend/lib/src/payments/handler.dart
- packages/espressocash_backend/lib/src/swap/handler.dart
- packages/espressocash_backend/pubspec.lock
- packages/espressocash_backend/pubspec.yaml
- packages/jsonrpc_client/pubspec.yaml
- packages/solana/pubspec.yaml
- packages/solana_mobile_client/example/pubspec.lock
- packages/solana_mobile_client/example/pubspec.yaml
- packages/solana_mobile_client/pubspec.yaml
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_mobile_wallet/example/pubspec.yaml
- packages/solana_mobile_wallet/pubspec.yaml
- packages/solana_seed_vault/example/pubspec.lock
- packages/solana_seed_vault/example/pubspec.yaml
- packages/solana_seed_vault/pubspec.yaml
> refactor: update lints

- packages/espressocash_backend/lib/src/payments/create_direct_payment.dart
- packages/espressocash_backend/lib/src/payments/create_direct_payment.freezed.dart
- packages/espressocash_backend/lib/src/payments/create_payment.dart
- packages/espressocash_backend/lib/src/payments/escrow_account.dart
- packages/espressocash_backend/lib/src/payments/receive_payment.dart
- packages/espressocash_backend/lib/src/swap/create_swap.dart
- packages/espressocash_backend/lib/src/swap/create_swap.freezed.dart
- packages/espressocash_backend/pubspec.lock
- packages/espressocash_backend/pubspec.yaml
- packages/espressocash_backend/test/payments/utils.dart
- updates latest solana version on espressocash_backend
> refactor: bump solana version

- packages/espressocash_app/android/app/src/main/AndroidManifest.xml
- packages/espressocash_app/lib/core/accounts/bl/account.dart
- packages/espressocash_app/lib/core/accounts/bl/ec_wallet.dart
- packages/espressocash_app/lib/core/transactions/resign_tx.dart
- packages/espressocash_app/lib/core/wallet.dart
- packages/espressocash_app/lib/features/activities/src/updater/bloc.dart
- packages/espressocash_app/lib/features/incoming_single_link_payments/src/bl/islp_bloc.dart
- packages/espressocash_app/lib/features/incoming_split_key_payments/src/bl/iskp_bloc.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/src/bl/bloc.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/bloc.dart
- packages/espressocash_app/lib/features/ramp/src/bl/on_ramp_bloc.dart
- packages/espressocash_app/lib/features/ramp/src/widgets/on_ramp_screen.dart
- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
- packages/espressocash_app/lib/features/swap/src/swap/swap_bloc.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_app/test/core/balances/balances_bloc_test.dart
- packages/espressocash_app/test/features/outgoing_direct_payments/bloc_test.dart
- packages/espressocash_app/test/features/ramp/on_ramp_bloc_test.dart
- packages/espressocash_app/test/golden/golden_test.dart
- packages/solana_seed_vault/android/build.gradle
- packages/solana_seed_vault/android/src/main/kotlin/com/solana/solana_seed_vault/WalletProxy.kt
- packages/solana_seed_vault/example/lib/bl/bloc.dart
- packages/solana_seed_vault/lib/src/seed_vault.dart
- packages/solana_seed_vault/test/seed_vault_wallet_test.dart
Added `ECWallet` interface to unlock other implementations.
> feat: abstract wallet interface

- packages/espressocash_app/lib/app/screens/authenticated/home_screen.dart
- packages/espressocash_app/lib/app/screens/authenticated/profile/profile_screen.dart
- packages/espressocash_app/lib/features/incoming_split_key_payments/src/widgets/first_part_ready_screen.dart
- packages/espressocash_app/lib/features/qr_scanner/src/widgets/qr_scanner_screen.dart
- packages/espressocash_app/lib/features/swap/src/flow.dart
- packages/espressocash_app/lib/main.dart
- packages/espressocash_app/lib/ui/theme.dart
System UI overlay style now follows the theme.
> fix: sytem overlay style

- packages/espressocash_app/lib/features/swap/src/route_repository.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/swap.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/swap.freezed.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/swap.g.dart
- packages/espressocash_backend/jupiter_aggregator/lib/src/model.freezed.dart
- packages/espressocash_backend/lib/src/swap/create_swap.dart
- packages/espressocash_backend/lib/src/swap/handler.dart
- packages/espressocash_backend/lib/src/swap/jupiter_repository.dart
Support legacy mode on BE + enable new swap txs in the app.
> feat: use new swap txs

- packages/espressocash_app/lib/main.dart
- packages/espressocash_app/lib/ui/splash_screen.dart
- packages/espressocash_app/pubspec.lock
> fix: bottom bar behaviour

- packages/solana/lib/src/rpc/extension.dart
> feat: provide default maxSupportedTransactionVersion

- packages/espressocash_app/lib/core/link_shortener.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/models/outgoing_split_key_payment.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/widgets/oskp_screen.dart
- packages/espressocash_app/lib/l10n/app_en.arb
> fix: improve error processing in outgoing payments

- packages/espressocash_app/lib/core/transactions/tx_sender.dart
Re-check tx if blockhash is already expired. It prevents the situation when the tx was submitted right after we check it but before blockhash is expired.
> fix: check tx in TxSender

- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/bloc.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/widgets/oskp_screen.dart
> fix: retry button behaviour

- packages/espressocash_app/README.md
> chore: add BrowserStack link

- packages/espressocash_app/lib/features/payment_request/src/widgets/link_request/request_note_screen.dart
Auto focus note textfield in new payment request
Fixes #811
> feat: auto focus on new request note

- packages/espressocash_app/lib/features/popular_tokens/src/data/popular_token_cache.dart
Maps popular token list (cache) to token list
> fix: popular token list cache mapping

- packages/espressocash_app/lib/core/cancelable_job.dart
- packages/espressocash_app/lib/features/incoming_single_link_payments/src/bl/tx_created_watcher.dart
- packages/espressocash_app/lib/features/incoming_single_link_payments/src/bl/tx_sent_watcher.dart
- packages/espressocash_app/lib/features/incoming_split_key_payments/src/bl/tx_created_watcher.dart
- packages/espressocash_app/lib/features/incoming_split_key_payments/src/bl/tx_sent_watcher.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/src/bl/tx_created_watcher.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/src/bl/tx_sent_watcher.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/cancel_tx_created_watcher.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/cancel_tx_sent_watcher.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/tx_confirmed_watcher.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/tx_created_watcher.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/tx_sent_watcher.dart
- packages/espressocash_app/lib/features/swap/src/swap/tx_created_watcher.dart
- packages/espressocash_app/lib/features/swap/src/swap/tx_sent_watcher.dart
- packages/espressocash_app/lib/main.dart
> feat: add performance monitoring for watchers

- packages/espressocash_app/lib/app/screens/authenticated/investments/components/investment_header.dart
Clicking on USDC header from home pushes to USDC Details page
Fixes #832
> feat: navigate to usdc token detail page from home

- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
Allow to only use USDC for ramp.
> feat: provide only USDC for ramp

- packages/espressocash_app/lib/features/outgoing_direct_payments/src/widgets/odp_details_screen.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/widgets/oskp_screen.dart
- packages/espressocash_app/lib/storybook/stories/timeline.dart
- packages/espressocash_app/lib/ui/timeline.dart
- Fix transfer progress screen items
<details><summary>Video</summary>
https://user-images.githubusercontent.com/19499575/221977500-98c25a47-9eb2-4294-852f-e463740392b3.mp4
</details>
> fix: update transfer progress screen

- packages/espressocash_app/lib/features/swap/src/create_swap/components/equivalent_header.dart
- packages/espressocash_app/lib/features/swap/src/create_swap/create_swap_screen.dart
- hide fee label when fetching
- disable button when fetching
Fixes #843
https://user-images.githubusercontent.com/28533130/221864709-cadae6b3-eca4-45e0-9a45-9cfda0fb546d.mp4
> feat: swap hide fees and button when searching route

- packages/espressocash_app/lib/features/swap/src/create_swap/components/token_dropdown.dart
- updated token dropdown in swap to use custom dropdown widget
https://user-images.githubusercontent.com/28533130/222143665-5d83146b-07d2-41fa-b10e-58f3ed8ec9ba.mp4
> fix: swap token dropdown splash

- .github/workflows/check_pr.yml
- .github/workflows/e2e_tests.yml
- .github/workflows/solana_coverage.yml
> ci: use flutter 3.7.7

- packages/espressocash_app/lib/app/screens/authenticated/activities/activities_screen.dart
- packages/espressocash_app/lib/app/screens/authenticated/profile/components/version_section.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/widgets/oskp_screen.dart
- packages/espressocash_app/lib/l10n/app_en.arb
- packages/espressocash_app/lib/ui/dialogs.dart
- Remove remaining hardcoded strings that are presented to user
> feat: remove hardcoded strings

- packages/espressocash_app/README.md
> docs: readme updates

- packages/espressocash_app/lib/features/incoming_split_key_payments/src/widgets/first_part_ready_screen.dart
- center contents of iskp first link screen
Fixes #882
> fix: center iskp screen content

- packages/espressocash_app/lib/features/incoming_split_key_payments/src/bl/iskp_repository.dart
- adds missing `slot` and `txFailureReason` 
- display proper message on iskp screen
https://user-images.githubusercontent.com/28533130/227116459-91da299f-e4ea-4c0d-b039-d654c94eeaa4.mp4
> fix: update iskp failure reason

- packages/espressocash_app/lib/app/screens/authenticated/investments/components/investment_header.dart
- packages/espressocash_app/lib/l10n/app_en.arb
- removes hardcoded height in investment header, fixes text overflow on longer texts
- minor: updated version string in profile
> fix: investment header overflow 

- packages/espressocash_app/lib/app/screens/authenticated/wallet_flow/wallet_flow_screen.dart
- packages/espressocash_app/lib/app/screens/authenticated/wallet_flow/wallet_main_screen.dart
- packages/espressocash_app/lib/core/presentation/format_amount.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/src/widgets/link_listener.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/src/widgets/odp_confirmation_screen.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/widgets/oskp_confirmation_screen.dart
- packages/espressocash_app/lib/storybook/stories/app/wallet_main_screen.dart
- packages/espressocash_app/lib/ui/amount_with_equivalent.dart
- Fixes USD to USDC conversion rate on wallet main flow (OSKP, ODP and Payment Request) and when paying a request.
<details><summary>Screenshots</summary>
</details>
> fix: usdc conversion rate on wallet main flow

- packages/espressocash_app/lib/app/screens/authenticated/home_screen.dart
Tapping on already active tab should pop route
Fixes #897
https://user-images.githubusercontent.com/28533130/227867965-59b32822-3f5e-4cbd-b1f4-e11a6e0e1995.mov
> feat: re tapping nav bar pops route

- packages/espressocash_app/lib/app/screens/authenticated/investments/investments_screen.dart
- Fixes blank home screen bug happening after onboarding and payment request creation due to keyboard interaction.
> fix: remove blank home screen after keyboard interaction

- packages/solana_seed_vault/android/build.gradle
> fix: bump seedvault-wallet-sdk from 0.2.6 to 0.2.7

- packages/solana_mobile_wallet/android/src/main/kotlin/com/solana/solana_mobile_wallet/ScenarioProxy.kt
- Fix mobile wallet exception handling for Kotlin 1.7
> fix: solana mobile wallet exception handling

- packages/espressocash_backend/bin/server.dart
- packages/espressocash_backend/lib/src/constants.dart
- packages/espressocash_backend/lib/src/handlers/common_link_handler.dart
- packages/espressocash_backend/lib/src/handlers/solana_handler.dart
Added support for espressocash links.
> feat: add new domain support

- packages/solana_mobile_client/example/lib/client.dart
- packages/solana_mobile_client/example/pubspec.lock
- packages/solana_mobile_wallet/example/lib/mobile_wallet/bloc.dart
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_seed_vault/example/lib/bl/utils.dart
- packages/solana_seed_vault/example/pubspec.lock
Switched to the latest solana version in examples.
> fix: use latest solana version

- packages/espressocash_app/lib/features/sign_in/src/widgets/get_started_screen.dart
- packages/espressocash_app/lib/ui/colors.dart
- packages/espressocash_app/lib/ui/splash_screen.dart
Update splash screen
Fixes #935
<details>
https://user-images.githubusercontent.com/28533130/233630828-f1cf7e11-8f2e-4d24-be93-f51a5efe0d5d.mp4
</details>
> feat: update splash screen

- packages/espressocash_app/lib/core/presentation/extensions.dart
- packages/espressocash_app/lib/features/token_chart/widgets/token_chart.dart
- updated token chart based on figma design
<details><summary>Video</summary>
https://user-images.githubusercontent.com/28533130/232512928-c281dc8d-93b4-4d6c-bb91-70fde6fd4e6f.mp4
</details>
> feat: updated token chart design

- packages/espressocash_backend/pubspec.lock
- packages/espressocash_backend/pubspec.yaml
> chore: update dependencies

- packages/espressocash_app/lib/features/swap/token_ext.dart
- packages/espressocash_app/lib/features/token_details/src/widgets/token_app_bar.dart
- packages/espressocash_app/lib/features/token_details/src/widgets/unavailable_token.dart
- packages/espressocash_app/lib/features/token_details/widgets/token_details_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/ui/info_icon.dart
added token unavailable to swap notice on token detail screen
<details><summary>iPhone SE</summary>
https://user-images.githubusercontent.com/28533130/233379138-e08d0eaa-0b97-4f2f-9104-4fd532ad0742.mp4
</details>
<details><summary>iPhone 14 Pro</summary>
https://user-images.githubusercontent.com/28533130/233379044-e70f6527-b462-4517-a128-b15fbb2f6376.mp4
</details>
> feat: add token unavailable to swap notice

- packages/espressocash_app/lib/app/screens/authenticated/wallet_flow/wallet_flow_screen.dart
- Sets minimum amount to 0.2 USDC to send and request
> feat: udpate minimum amount to send and request

- codemagic.yaml
- packages/espressocash_app/android/app/build.gradle
Added Codemagic configuration.
> ci: integrate codemagic

- packages/espressocash_app/android/app/src/main/AndroidManifest.xml
- packages/espressocash_app/ios/Runner/Runner.entitlements
- packages/espressocash_app/lib/config.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/src/widgets/link_listener.dart
- packages/espressocash_app/lib/features/payment_request/models/payment_request.dart
- packages/espressocash_backend/lib/src/constants.dart
- packages/espressocash_backend/lib/src/handlers/solana_handler.dart
Update solanapay host to use `espressocash.com`.
> feat: update solanapay host

- packages/espressocash_backend/lib/src/apps.dart
> feat: update team id

- packages/espressocash_app/lib/core/router_wrapper.dart
- packages/espressocash_app/lib/di.dart
- packages/espressocash_app/lib/features/sign_in/routes.dart
- packages/espressocash_app/lib/features/sign_in/src/bl/sign_in_bloc.dart
- packages/espressocash_app/lib/features/sign_in/src/widgets/get_started_screen.dart
- packages/espressocash_app/lib/features/sign_in/src/widgets/sign_in_flow_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_app/test/golden/golden_test.dart
Removed creating a wallet with Saga, there's now one button "Sign in with Saga".
> feat: update sign in with saga flow

- packages/espressocash_app/lib/features/token_chart/widgets/token_chart.dart
- packages/espressocash_app/lib/features/token_details/src/widgets/token_app_bar.dart
- packages/espressocash_app/lib/ui/token_icon.dart
- removes border on circle dot in chart
- updates tip stroke for line chart
- make right price tiles smaller 
- update icons to be circular
- remove excess padding on token header
- make chart interval indicators static
<details>
https://user-images.githubusercontent.com/28533130/235405021-b53a0f8f-03c6-4d25-bbdb-3ca041f205f4.mp4
</details>
> feat: token details page enhancements 

- .github/workflows/check_pr.yml
- packages/solana/test/programs/stake_program/stake_program_test.dart
Fixed tests to use increased stake amount, updated Dart version in CI.
> test: fix stake tests

- .github/workflows/check_pr.yml
Adds specific Dart version for actions
> ci: add dart version for actions

- packages/espressocash_app/android/app/build.gradle
- packages/espressocash_app/android/build.gradle
- packages/espressocash_app/ios/Podfile
- packages/espressocash_app/ios/Podfile.lock
- packages/espressocash_app/ios/Runner.xcodeproj/project.pbxproj
- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> feat: update ramp network to latest version

- packages/espressocash_app/lib/ui/app_bar.dart
- packages/espressocash_app/lib/ui/back_button.dart
updates checking on Navigator on back button
> fix: back button on app locked screen

- .github/workflows/solana_coverage.yml
fixes metaplex tests for solana_coverage workflow
> ci: fix metaplex tests on solana coverage

- packages/espressocash_app/Makefile
- packages/espressocash_app/saga_publishing/.asset-manifest.json
- packages/espressocash_app/saga_publishing/config.yaml
New release and updated makefile.
> build: create new saga release

- packages/espressocash_app/lib/core/balances/bl/balances_bloc.dart
- packages/espressocash_app/lib/core/transactions/resign_tx.dart
- packages/espressocash_app/lib/features/mobile_wallet/src/bl/bloc.dart
- packages/espressocash_app/lib/features/payment_request/src/widgets/link_details/flow.dart
- packages/espressocash_app/lib/features/payment_request/widgets/payment_request_verifier.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_app/test/golden/golden_test.dart
> refactor: update dfunc

- packages/borsh/pubspec.yaml
- packages/borsh_annotation/pubspec.yaml
- packages/espressocash_app/lib/features/incoming_split_key_payments/src/bl/tx_created_watcher.dart
- packages/espressocash_app/lib/features/incoming_split_key_payments/src/bl/tx_sent_watcher.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/tx_sent_watcher.dart
- packages/espressocash_app/lib/ui/amount_keypad/amount_keypad.dart
- packages/espressocash_app/lib/ui/theme.dart
- packages/espressocash_app/lib/ui/webview_screen.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_backend/espressocash_api/pubspec.yaml
- packages/espressocash_backend/jupiter_aggregator/pubspec.yaml
- packages/espressocash_backend/pubspec.lock
- packages/espressocash_backend/pubspec.yaml
- packages/jsonrpc_client/pubspec.yaml
- packages/solana/pubspec.yaml
- packages/solana_mobile_client/example/pubspec.lock
- packages/solana_mobile_client/example/pubspec.yaml
- packages/solana_mobile_client/lib/src/mobile_wallet_adapter_client.dart
- packages/solana_mobile_client/pubspec.yaml
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_mobile_wallet/example/pubspec.yaml
- packages/solana_mobile_wallet/pubspec.yaml
- packages/solana_seed_vault/example/pubspec.lock
- packages/solana_seed_vault/example/pubspec.yaml
- packages/solana_seed_vault/pubspec.yaml
Bumped linter version and fixed new warnings.
> refactor: bump linter

- packages/espressocash_app/lib/features/sign_in/src/widgets/components/terms_disclaimer.dart
- packages/espressocash_app/lib/features/sign_in/src/widgets/get_started_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/main.dart
- packages/espressocash_app/lib/ui/bullet_item.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_app/test/golden/golden_test.dart
- packages/espressocash_app/test/golden/utils.dart
- packages/espressocash_app/test/golden/wrapper.dart
Updated get started screen, integrated screenutil and device preview support.
> feat: update get started screen

- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/l10n/intl_es.arb
- packages/espressocash_app/lib/l10n/intl_fr.arb
- packages/espressocash_app/lib/l10n/intl_pt.arb
Exported the most recent translations from Localizely
> chore: update translations

- packages/espressocash_app/lib/features/profile/screens/profile_screen.dart
Updated safe area paddings in profile screen.
> fix: padding in ProfileScreen

- packages/espressocash_app/lib/features/payment_request/module.dart
Unnecessary nested `LogoutListener` removed.
> fix: remove duplicated LogoutListener

- packages/espressocash_backend/lib/src/escrow_payments/cancel_payment.dart
- packages/espressocash_backend/lib/src/escrow_payments/create_payment.dart
- packages/espressocash_backend/lib/src/escrow_payments/handler.dart
- packages/espressocash_backend/lib/src/escrow_payments/receive_payment.dart
- packages/espressocash_backend/lib/src/payments/create_payment.dart
- packages/espressocash_backend/lib/src/payments/handler.dart
- packages/espressocash_backend/lib/src/payments/receive_payment.dart
- packages/espressocash_backend/lib/src/swap/create_swap.dart
- packages/espressocash_backend/pubspec.lock
- packages/espressocash_backend/pubspec.yaml
- packages/espressocash_backend/test/escrow_payments/cancel_payment_test.dart
- packages/espressocash_backend/test/escrow_payments/create_payment_test.dart
- packages/espressocash_backend/test/escrow_payments/receive_payment_test.dart
- packages/espressocash_backend/test/payments/create_payment_test.dart
- packages/espressocash_backend/test/payments/escrow_account_test.dart
- packages/espressocash_backend/test/payments/receive_payment_test.dart
> refactor: update dependencies

- packages/espressocash_app/lib/features/onboarding/screens/onboarding_flow_screen.dart
- packages/espressocash_app/lib/features/onboarding/widgets/onboarding_notice.dart
- packages/espressocash_app/lib/features/sign_in/screens/get_started_screen.dart
- packages/espressocash_app/lib/features/sign_in/screens/restore_account_screen.dart
- packages/espressocash_app/lib/features/sign_in/screens/sign_in_flow_screen.dart
- packages/espressocash_app/lib/routes.dart
- packages/espressocash_app/test/golden/golden_test.dart
> fix: sign-in flow

- .fvm/fvm_config.json
- .github/workflows/check_pr.yml
- .github/workflows/e2e_tests.yml
- codemagic.yaml
> refactor: migrate to Flutter 3.10.5

- packages/espressocash_app/lib/features/onboarding/widgets/onboarding_notice.dart
> fix: center button in onboarding notice

- packages/espressocash_app/lib/features/app_lock/screens/app_lock_setup_flow_screen.dart
- packages/espressocash_app/lib/features/backup_phrase/screens/backup_phrase_flow_screen.dart
- packages/espressocash_app/lib/features/profile/screens/country_picker_screen.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> fix: add padding to country selector

- packages/espressocash_app/lib/core/amount.dart
- packages/espressocash_app/lib/core/currency.dart
- packages/espressocash_app/lib/core/presentation/format_amount.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/screens/oskp_confirmation_screen.dart
- packages/espressocash_app/lib/features/payment_request/services/create_payment_request_bloc.dart
Removed map/when methods from `Currency` and `Amount`.
> refactor: clean Amount and Currency

- packages/espressocash_app/lib/core/async_snapshot.dart
- packages/espressocash_app/lib/core/fee_label.dart
- packages/espressocash_app/lib/core/flow.dart
- packages/espressocash_app/lib/core/processing_state.dart
- packages/espressocash_app/lib/features/balances/widgets/refresh_balance_wrapper.dart
- packages/espressocash_app/lib/features/payment_request/screens/link_request_flow_screen.dart
- packages/espressocash_app/lib/features/payment_request/services/create_payment_request_bloc.dart
- packages/espressocash_app/lib/features/popular_tokens/widgets/popular_token_list.dart
- packages/espressocash_app/lib/features/sign_in/screens/sign_in_flow_screen.dart
- packages/espressocash_app/lib/features/swap/screens/create_swap_screen.dart
- packages/espressocash_app/lib/features/token_details/screens/token_details_screen.dart
- packages/espressocash_app/lib/features/token_search/screens/token_search_screen.dart
- packages/espressocash_app/test/golden/golden_test.dart
> refactor: migrate some freezed classes to sealed

- packages/borsh/pubspec.yaml
- packages/borsh_annotation/pubspec.yaml
- packages/espressocash_app/lib/features/incoming_split_key_payments/widgets/pending_iskp_listener.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/services/oskp_service.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/services/tx_ready_watcher.dart
- packages/espressocash_app/lib/features/swap/screens/create_swap_screen.dart
- packages/espressocash_app/lib/features/wallet_flow/screens/wallet_flow_screen.dart
- packages/espressocash_app/lib/features/wallet_flow/screens/wallet_main_screen.dart
- packages/espressocash_app/lib/ui/button.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- packages/espressocash_backend/espressocash_api/pubspec.yaml
- packages/espressocash_backend/jupiter_aggregator/pubspec.yaml
- packages/espressocash_backend/lib/src/handlers/common_link_handler.dart
- packages/espressocash_backend/lib/src/swap/jupiter_repository.dart
- packages/espressocash_backend/pubspec.lock
- packages/espressocash_backend/pubspec.yaml
- packages/espressocash_backend/test/payments/utils.dart
- packages/jsonrpc_client/pubspec.yaml
- packages/solana/pubspec.yaml
- packages/solana_mobile_client/example/pubspec.lock
- packages/solana_mobile_client/example/pubspec.yaml
- packages/solana_mobile_client/pubspec.yaml
- packages/solana_mobile_wallet/example/pubspec.lock
- packages/solana_mobile_wallet/example/pubspec.yaml
- packages/solana_mobile_wallet/pubspec.yaml
- packages/solana_seed_vault/example/pubspec.lock
- packages/solana_seed_vault/example/pubspec.yaml
- packages/solana_seed_vault/pubspec.yaml
> refactor: update linter

- packages/espressocash_app/lib/core/amount.dart
- packages/espressocash_app/lib/features/conversion_rates/services/amount_ext.dart
- packages/espressocash_app/lib/features/conversion_rates/services/convert_to_fiat.dart
- packages/espressocash_app/lib/features/conversion_rates/services/convert_to_usd.dart
- packages/espressocash_app/lib/features/conversion_rates/widgets/amount_with_equivalent.dart
- packages/espressocash_app/lib/features/conversion_rates/widgets/context_ext.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/widgets/link_listener.dart
- packages/espressocash_app/lib/features/outgoing_split_key_payments/screens/oskp_confirmation_screen.dart
- packages/espressocash_app/lib/features/payment_request/services/create_payment_request_bloc.dart
- packages/espressocash_app/lib/features/qr_scanner/widgets/build_context_ext.dart
- packages/espressocash_app/lib/features/wallet_flow/screens/wallet_flow_screen.dart
> fix: make amount formatting more consistent

- packages/espressocash_app/l10n.yaml
- packages/espressocash_app/lib/features/token_chart/data/repository.dart
- packages/espressocash_app/lib/features/token_chart/models/chart_interval.dart
- packages/espressocash_app/lib/features/token_chart/services/bloc.dart
- packages/espressocash_app/lib/features/token_chart/widgets/token_chart.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/l10n/intl_es.arb
- packages/espressocash_app/lib/l10n/l10n.dart
> fix: remove 1d from token chart

- packages/espressocash_app/lib/features/ramp/kado.dart
> fix: kado onramp parameters

- packages/espressocash_app/lib/config.dart
- packages/espressocash_app/lib/features/ramp/guardarian.dart
- packages/espressocash_app/lib/features/ramp/kado.dart
- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
> feat: Integrate guardarian onramp

- packages/espressocash_app/android/app/src/main/AndroidManifest.xml
- packages/espressocash_app/ios/Podfile
- packages/espressocash_app/ios/Podfile.lock
- packages/espressocash_app/lib/features/ramp/guardarian.dart
- packages/espressocash_app/lib/features/ramp/kado.dart
- packages/espressocash_app/lib/ui/web_view_screen.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> feat: migrate to flutter_inappwebview

- packages/espressocash_app/lib/features/ramp/guardarian.dart
- packages/espressocash_app/lib/features/ramp/kado.dart
- packages/espressocash_app/lib/features/ramp/models/profile_data.dart
- packages/espressocash_app/lib/features/ramp/ramp_network.dart
- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
- packages/espressocash_app/lib/ui/web_view_screen.dart
> feat: provide email to onramp partners

- packages/espressocash_app/lib/features/ramp/kado/src/data/kado_api_client.dart
- packages/espressocash_app/lib/features/ramp/kado/src/services/kado_on_ramp_order_watcher.dart
> fix: kado order status

- packages/espressocash_app/lib/features/ramp/data/on_ramp_order_service.dart
> fix: clear on-ramp orders on logout

- packages/espressocash_app/lib/features/investments/screens/investments_screen.dart
> fix: app bar on investments screen

- packages/espressocash_app/lib/core/link_payments.dart
- packages/espressocash_app/lib/features/payment_request/models/payment_request.dart
- fix link format for payment request
> fix: payment request link format

- packages/solana_mobile_client/android/src/main/kotlin/com/solana/solana_mobile_client/ApiLocalAssociationScenario.kt
> fix: thread starting

- packages/espressocash_app/lib/main.dart
- reduced native splash duration
> feat: reduce splash duration

- packages/espressocash_app/android/app/build.gradle
- packages/espressocash_app/lib/ui/web_view_screen.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- updates `flutter_inappwebview` version
- sets `allowsInlineMediaPlayback` to true 
- sets `iframeAllowFullscreen` to false
> fix: kado webview update

- packages/espressocash_app/ios/Podfile.lock
- packages/espressocash_app/lib/features/mobile_wallet/services/bloc.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> refactor: bump dependencies

- packages/espressocash_app/lib/features/qr_scanner/widgets/build_context_ext.dart
Payment request amount was wrongly calculated because it was assumed to be in fiat currency, even if passed as crypto amount.
> fix: payment request amount

- packages/espressocash_app/lib/ui/timeline.dart
- fixes gap on timeline on some android devices
- root cause: https://github.com/flutter/flutter/issues/14288, fix is workarounds stated in issue
> fix: timeline gap

- packages/espressocash_app/lib/features/profile/screens/profile_screen.dart
- packages/espressocash_app/lib/features/qr_scanner/models/qr_address_data.dart
- packages/espressocash_app/lib/features/qr_scanner/widgets/build_context_ext.dart
- packages/espressocash_app/test/features/qr_scanner/qr_scanner_bloc_test.dart
- updates profile qr code to address only
- removes name on qr address data
Fixes https://github.com/espresso-cash/espresso-cash-public/issues/1126
> feat: update profile qr code

- packages/espressocash_app/lib/config.dart
> feat: remove hardcoded keys

- packages/espressocash_app/lib/features/sign_in/screens/get_started_screen.dart
- packages/espressocash_app/lib/ui/colors.dart
- packages/espressocash_app/lib/ui/splash_screen.dart
- update splash screen background color to match native splash 
> fix: splash screen background color

- packages/espressocash_app/lib/ui/web_view_screen.dart
call onLoaded even if title is not null
> fix: webview onLoaded call

- packages/espressocash_app/lib/features/activities/data/transaction_repository.dart
- packages/espressocash_app/lib/features/ramp/kado/data/kado_api_client.dart
- packages/espressocash_app/lib/features/ramp/kado/services/kado_on_ramp_order_watcher.dart
- adds offramp and onramp transaction matching
- adds `txHash` for Kado
> feat: add ramp transaction tiles

- packages/espressocash_app/lib/features/incoming_link_payments/data/ilp_repository.dart
- packages/espressocash_app/lib/features/incoming_link_payments/models/incoming_link_payment.dart
- packages/espressocash_app/lib/features/incoming_link_payments/screens/incoming_link_payment_screen.dart
- packages/espressocash_app/lib/features/incoming_link_payments/services/tx_sent_watcher.dart
- packages/espressocash_app/lib/features/transactions/widgets/transfer_success.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
add fee message on incoming link payment
Fixes #1156
> feat: add fee message on incoming link payment

- packages/espressocash_app/assets/icons/timeline-check.svg
- packages/espressocash_app/assets/icons/timeline-fail.svg
- packages/espressocash_app/lib/ui/colors.dart
- packages/espressocash_app/lib/ui/timeline.dart
- updated indicator icons
- updated colors hex
- updated tile alignment
- updated active animated indicator color
<details>
https://github.com/espresso-cash/espresso-cash-public/assets/28533130/cb57efe1-542b-4dbf-aaa1-0f07a278a78b
</details>
> feat: timeline widget updates

- packages/espressocash_app/build.yaml
- packages/espressocash_backend/build.yaml
- packages/espressocash_backend/dln_api/lib/src/models/dto.freezed.dart
- packages/espressocash_backend/dln_api/lib/src/models/models.freezed.dart
- packages/espressocash_backend/espressocash_api/build.yaml
- packages/espressocash_backend/espressocash_api/lib/src/client.g.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/add_funds.freezed.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/add_funds.g.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/create_payment.freezed.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/create_payment.g.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/get_fees.freezed.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/get_fees.g.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/scalex.freezed.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/scalex.g.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/swap.freezed.dart
- packages/espressocash_backend/espressocash_api/lib/src/dto/swap.g.dart
- packages/espressocash_backend/jupiter_aggregator/build.yaml
- packages/espressocash_backend/jupiter_aggregator/lib/src/client.g.dart
- packages/espressocash_backend/lib/src/scalex/client/client.g.dart
- added build.yaml order for generated files
> fix: added generator build order

- packages/espressocash_app/lib/features/popular_tokens/data/repository.dart
- packages/espressocash_app/tool/update_token_list.dart
- added JITO
- updated solana token list export path
> feat: updated popular token list

- packages/espressocash_app/lib/l10n/intl_en.arb
minor label change
Fixes #1176
> feat: minor label update

- packages/espressocash_app/lib/features/ramp/services/off_ramp_order_service.dart
fixes infinite loop bug when canceling cash out. 
> fix: cancel cash out bug

- packages/espressocash_app/lib/core/currency.dart
- packages/espressocash_app/lib/features/popular_tokens/widgets/popular_token_list.dart
- update spacing and text
- updated max decimals to 7
- added black bg for transparent png logo
> feat: popular token ui

- packages/espressocash_app/lib/ui/splash_screen.dart
- update flutter splash to match native gradient
> feat: update flutter splash screen

- packages/espressocash_app/lib/l10n/intl_en.arb
> feat: minor wallet label update

- packages/espressocash_app/lib/features/fees/models/fee_type.dart
- packages/espressocash_app/lib/features/fees/src/services/fee_calculator.dart
- packages/espressocash_app/lib/features/ramp/services/off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/src/widgets/off_ramp_confirmation.dart
- packages/espressocash_app/lib/storybook/stories/screens/off_ramp_order_screen.dart
> feat: update fee calculation for withdraw

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/user.dart
- packages/espressocash_api/lib/src/dto/user.freezed.dart
- packages/espressocash_api/lib/src/dto/user.g.dart
> feat: add endpoint for storing wallet country

- packages/espressocash_app/lib/main.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- remove 1 second delay
- move splash package to dev depdency
> refactor: splash dependency

- packages/espressocash_app/android/app/src/main/AndroidManifest.xml
- packages/espressocash_app/lib/ui/web_view_screen.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- update webview dependency to latest stable version
- update webview config for WebRTC
- update android permissions 
Fixes #1227
> fix: webview camera

- packages/espressocash_api/lib/src/dto/dln_payment.dart
- packages/espressocash_api/lib/src/dto/dln_payment.freezed.dart
- packages/espressocash_api/lib/src/dto/dln_payment.g.dart
- update from `String` to `int`
> refactor: update dln endpoint datatype

- packages/espressocash_app/lib/features/investments/widgets/portfolio_tile.dart
- packages/espressocash_app/lib/features/investments/widgets/portfolio_widget.dart
- fix bug on showing incorrect token balances
> fix: incorrect token balance

- packages/espressocash_app/lib/features/intercom/services/intercom_service.dart
> fix: intercom initialization

- packages/espressocash_api/lib/src/dto/scalex.dart
- packages/espressocash_api/lib/src/dto/scalex.freezed.dart
- packages/espressocash_api/lib/src/dto/scalex.g.dart
> feat: added scalex onramp fees

- packages/espressocash_app/lib/features/profile/data/profile_repository.dart
- packages/espressocash_app/lib/features/profile/screens/manage_profile_screen.dart
- packages/espressocash_app/lib/features/profile/screens/profile_screen.dart
- packages/espressocash_app/lib/features/profile/widgets/pick_profile_picture.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/ui/pick_image_container.dart
- packages/espressocash_app/lib/ui/text_field.dart
- packages/espressocash_app/lib/ui/user_avatar.dart
Adds last name field to the profile screen and synced with the design. It doesn't add the required profile onboarding step yet.
> feat: add last name

- packages/espressocash_app/lib/features/outgoing_dln_payments/screens/details_screen.dart
- packages/espressocash_app/lib/features/outgoing_link_payments/screens/olp_screen.dart
- packages/espressocash_app/lib/features/payment_request/screens/share_payment_request_screen.dart
- packages/espressocash_app/lib/features/profile/widgets/danger_section.dart
- packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/l10n/intl_es.arb
- packages/espressocash_app/lib/l10n/intl_fr.arb
- packages/espressocash_app/lib/l10n/intl_pt.arb
- packages/espressocash_app/lib/l10n/intl_ru.arb
- packages/espressocash_app/lib/ui/button.dart
- packages/espressocash_app/lib/ui/dialogs.dart
- updated confirmation dialog theme and layout
- added CpButton mute theme
- removed delete wallet l10n
<details>
</details>
> feat: update confirmation dialog theme

- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
removes Guardarian for US on ramp
> feat: remove Guardarian for US on ramp

- packages/espressocash_app/lib/features/onboarding/data/onboarding_repository.dart
- packages/espressocash_app/lib/features/transactions/services/tx_sender.dart
check current countries if from ofac blocklisted 
Fixes #1312
> feat: ensure current countries not ofac blocklisted

- packages/espressocash_app/lib/features/ramp/partners/scalex/widgets/launch.dart
removes scalex offramp fee label
> feat: remove scalex offramp fee

- packages/espressocash_app/lib/main.dart
clear secure storage on new install
> fix: clear secure storage on first run

- packages/espressocash_app/lib/features/ramp/partners/coinflow/data/coinflow_api_client.dart
- packages/espressocash_app/lib/features/ramp/partners/coinflow/widgets/launch.dart
updates flow to also redirect to external verification when no linked accounts
> fix: coinflow kyc flow 

- packages/espressocash_landing/Makefile
- packages/espressocash_landing/web/index.html
- fix landing build script
- remove unused script
> fix: espresso landing build script

- packages/espressocash_app/lib/features/payment_request/widgets/share_qr_code.dart
- packages/espressocash_app/lib/features/qr_scanner/models/qr_scanner_request.dart
- updates qr code to be dynamic link
- updates in app qr scanner to read request dynamic link
> feat: update payment request link

- packages/espressocash_app/lib/features/activities/widgets/payment_request_tile.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/l10n/intl_es.arb
- packages/espressocash_app/lib/l10n/intl_fr.arb
- packages/espressocash_app/lib/l10n/intl_pt.arb
- packages/espressocash_app/lib/l10n/intl_ru.arb
updates payment request activity tile
> feat: payment request tile title update

- packages/espressocash_app/lib/features/ramp/models/ramp_partner.dart
- packages/espressocash_app/lib/features/ramp/partners/scalex/widgets/launch.dart
fix minimum amount inconsistency
Fixes #1372
> fix: scalex minimum amount

- packages/espressocash_app/lib/features/feature_flags/services/feature_flags_manager.dart
- packages/espressocash_app/lib/features/payment_request/models/payment_request.dart
- packages/espressocash_app/lib/features/payment_request/services/payment_request_service.dart
adds ff to update request link to show dln feature
> feat: add feature flag for incoming dln request

- packages/espressocash_app/lib/features/authenticated/screens/home_screen.dart
- packages/espressocash_app/lib/features/dynamic_links/data/dynamic_links_client.dart
- packages/espressocash_app/lib/features/dynamic_links/services/dynamic_links_notifier.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/widgets/link_listener.dart
- packages/espressocash_app/lib/features/sign_in/screens/get_started_screen.dart
- packages/espressocash_app/lib/utils/solana_pay.dart
- resolve incoming shortened deep links
- shows loader when calling unshorten api
Fixes #1417
<details>
https://github.com/espresso-cash/espresso-cash-public/assets/28533130/58f7f02c-cba8-4cbb-a0a0-5fdfb282deed
</details>
> feat: resolve incoming shortened deep links

- packages/espressocash_app/lib/features/qr_scanner/models/qr_address_data.dart
update evm parsing to include addresses inside deeplink (ie ethereum:addrr)
Fixes #1390
> feat: update evm qr parsing

- packages/espressocash_app/lib/features/payment_request/widgets/share_request.dart
- packages/espressocash_app/lib/features/wallet_flow/widgets/pay_main_page.dart
- packages/espressocash_app/lib/ui/share_link.dart
adjusted padding on request and pay screens
> feat: minor padding adjustment

- packages/espressocash_app/lib/features/dynamic_links/services/dynamic_links_notifier.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
validates hash of shortened link
> feat: validate shortened link hash

- packages/espressocash_app/ios/Podfile.lock
- packages/espressocash_app/lib/di.dart
- packages/espressocash_app/lib/features/analytics/analytics_manager.dart
- packages/espressocash_app/lib/features/balances/services/balances_bloc.dart
- packages/espressocash_app/lib/features/incoming_link_payments/widgets/pending_ilp_listener.dart
- packages/espressocash_app/lib/features/outgoing_direct_payments/widgets/extensions.dart
- packages/espressocash_app/lib/features/outgoing_link_payments/widgets/extensions.dart
- packages/espressocash_app/lib/features/profile/service/update_profile.dart
- packages/espressocash_app/lib/features/profile/service/wallet_service.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> feat: integrate mixpanel

- packages/espressocash_app/lib/ui/web_view_screen.dart
show loading title on initial load
Fixes #1428
> feat: show loading title on webview

- packages/espressocash_app/lib/ui/text_button.dart
> feat: increase text button tap area

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/gas.dart
- packages/espressocash_api/lib/src/dto/gas.freezed.dart
- packages/espressocash_api/lib/src/dto/gas.g.dart
> feat: add gas fee endpoint

- packages/espressocash_app/lib/features/transaction_request/widgets/extensions.dart
- packages/solana/lib/src/solana_pay/solana_client_ext.dart
- fixes transaction pay request bug
- adds better balance verification check
> fix: transaction request fixes

- packages/espressocash_app/lib/features/authenticated/widgets/portfolio_widget.dart
- packages/espressocash_app/lib/features/balances/data/token_balance_repository.dart
- packages/espressocash_app/lib/features/balances/services/balances_bloc.dart
- packages/espressocash_app/lib/features/conversion_rates/data/repository.dart
- packages/espressocash_app/lib/features/conversion_rates/services/watch_token_total_balance.dart
- packages/espressocash_app/lib/features/tokens/token_list.dart
ignores usdc on portfolio and crypto total
Fixes #1470
> fix: ignore usdc token on crypto portfolio

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/durable_transactions.dart
- packages/espressocash_api/lib/src/dto/durable_transactions.freezed.dart
- packages/espressocash_api/lib/src/dto/durable_transactions.g.dart
- packages/espressocash_api/lib/src/dto/get_rates.freezed.dart
- packages/espressocash_api/lib/src/dto/priority_fees.dart
- packages/espressocash_api/lib/src/dto/priority_fees.freezed.dart
- packages/espressocash_api/lib/src/dto/priority_fees.g.dart
- packages/espressocash_api/lib/src/dto/scalex.freezed.dart
- packages/espressocash_api/lib/src/dto/scalex.g.dart
- adds priority fee api endpoints
- updates `submitDurableTx` to return signature
> feat: update nonce and priority fee api

- packages/espressocash_app/lib/features/incoming_link_payments/widgets/extensions.dart
- packages/espressocash_app/lib/features/outgoing_link_payments/widgets/extensions.dart
- packages/espressocash_app/lib/features/transactions/services/tx_confirm.dart
adds sentry logs when creating transactions for links (OLP, ILP)
Fixes #1509
> feat: add logging for link tx creation

- packages/espressocash_app/android/app/build.gradle
update android target version to 34
Fixes #1520
> feat: android target sdk version to 34

- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/moneygram.dart
- packages/espressocash_api/lib/src/dto/moneygram.freezed.dart
- packages/espressocash_api/lib/src/dto/moneygram.g.dart
> feat: moneygram api update

- packages/espressocash_app/lib/features/ramp/partners/coinflow/widgets/launch.dart
checks if Coinflow requires additional verification, automatically redirects to external browser if needed
> fix: coinflow additional verification redirect

- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
Added flutter_inappwebview_android dependency override
> fix: Temporary change for webview package dependency

- packages/espressocash_app/lib/features/ramp/partners/moneygram/data/moneygram_client.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/widgets/launch.dart
- packages/espressocash_app/lib/features/stellar/constants.dart
> fix: moneygram stellar config

- packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart
- packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/ui/status_screen.dart
> fix: status screen UI theming

- packages/espressocash_app/lib/features/analytics/analytics_manager.dart
- packages/espressocash_app/lib/features/payment_request/services/payment_request_service.dart
- packages/espressocash_app/test/stub_analytics_manager.dart
Added logs of payment request link creation to mixpanel
Fixes #1545 
> feat: request link creation to mixpanel logs

- packages/espressocash_app/lib/features/activities/data/transaction_repository.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/data/allbridge_client.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart
- packages/espressocash_app/lib/features/ramp/services/on_ramp_order_service.dart
- packages/espressocash_app/lib/features/stellar/service/stellar_client.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/utils/errors.dart
- fix for moneygram deposit bug
- added logs to sentry
- updates moneygram offramp tx matching
- adds cancel button on moneygram deposits
> fix: moneygram ramp fixes

- packages/espressocash_api/lib/src/exception.dart
- packages/espressocash_api/lib/src/exception.g.dart
updates ec api errors
Fixes #1529
> feat: update api errors

- packages/espressocash_app/lib/features/analytics/analytics_manager.dart
- packages/espressocash_app/lib/features/ramp/partners/coinflow/services/coinflow_off_ramp_order_watcher.dart
- packages/espressocash_app/lib/features/ramp/partners/coinflow/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/partners/kado/services/kado_off_ramp_order_watcher.dart
- packages/espressocash_app/lib/features/ramp/partners/kado/services/kado_on_ramp_order_watcher.dart
- packages/espressocash_app/lib/features/ramp/partners/kado/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/partners/scalex/services/scalex_off_ramp_order_watcher.dart
- packages/espressocash_app/lib/features/ramp/partners/scalex/services/scalex_on_ramp_order_watcher.dart
- packages/espressocash_app/lib/features/ramp/partners/scalex/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/services/off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/services/on_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
- packages/espressocash_app/test/stub_analytics_manager.dart
adds ramp analytics to mixpanel
Fixes #1548
> feat: add ramp analytics

- packages/espressocash_app/lib/features/currency/models/amount.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- updates moneygram offramp amount to floor from bridged amount
- update offramp text and animation
> fix: moneygram offramp bridge amount

- packages/espressocash_app/lib/features/stellar_recovery/widgets/stellar_recovery_notice.dart
updates listening of recovery service from widget from async to sync
> fix: stellar recovery service init

- packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart
- packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
update moneygram ramp bridge text to include estimated time
> feat: update moneygram bridge text

- packages/solana/lib/src/rpc/dto/return_data.dart
Update parsing of data from ReturnData
Fixes #1567
> fix: ReturnData parsing

- packages/espressocash_app/lib/features/authenticated/screens/main_screen.dart
- packages/espressocash_app/lib/features/authenticated/widgets/refresh_balance_wrapper.dart
- packages/espressocash_app/lib/ui/home_tile.dart
- conversion rates initial fetching fix
- small ui bug fixes
> fix: home screen fixes

- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
enable all moneygram supported countries (https://docs.google.com/spreadsheets/d/1batl_ykVzF9czFpYoW3zYDSLaHu4S3KnaFUoYaS-XdM/edit?pli=1&gid=0#gid=0)
> feat: update moneygram countries

- packages/espressocash_app/lib/features/ramp/partners/scalex/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart
> fix: scalex onramp

- packages/espressocash_app/lib/features/ramp/partners/coinflow/widgets/launch.dart
logs coinflow exception to Sentry
> feat: log coinflow exception

- packages/espressocash_app/lib/features/authenticated/screens/authenticated_flow_screen.dart
- packages/espressocash_app/lib/features/onboarding/screens/profile_screen.dart
- packages/espressocash_app/lib/features/onboarding/screens/view_recovery_phrase_screen.dart
- packages/espressocash_app/lib/features/sign_in/screens/sign_in_flow_screen.dart
Fix for AuthenticatedFlowScreen navigation
Fixes #___
> fix: navigation

- packages/espressocash_app/lib/features/ramp/screens/ramp_amount_screen.dart
- packages/espressocash_app/lib/features/ramp/widgets/error_chip.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- added minimum amount notice state
- updated screen paddings
<details>
https://github.com/user-attachments/assets/63706db0-933f-4a26-a0fd-4d49709be03b
</details>
<details>
https://github.com/user-attachments/assets/ca8fc90e-1465-4a99-bdce-4130fdd3e718
</details>
> feat: ramp amount screen updates

- packages/espressocash_app/lib/features/conversion_rates/data/repository.dart
fix for fetching fiat rates on app start
> fix: fetch fiat rates on start

- packages/espressocash_api/lib/src/dto/moneygram.dart
- packages/espressocash_api/lib/src/dto/moneygram.freezed.dart
- packages/espressocash_api/lib/src/dto/moneygram.g.dart
- packages/espressocash_api/pubspec.yaml
> feat: update moneygram api endpoints

- packages/espressocash_app/lib/features/ramp/screens/ramp_onboarding_screen.dart
- packages/espressocash_app/lib/features/ramp/widgets/ramp_page.dart
- packages/espressocash_app/lib/ui/form_page.dart
Changes style for ramp onboarding screen to be consistent for deposit and withdrawal.
<details>
</details>
> feat: ramp onboarding screen updates

- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_fees_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/partners/scalex/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/screens/ramp_amount_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- update moneygram deposit input to USDC
- remove Partner Fee label
> feat: moneygram deposit

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/fiat_rate.dart
- packages/espressocash_api/lib/src/dto/fiat_rate.freezed.dart
- packages/espressocash_api/lib/src/dto/fiat_rate.g.dart
- packages/espressocash_api/lib/src/dto/moneygram.freezed.dart
add fetching fiat rates endpoint
> feat: add fetching fiat rates endpoint

- packages/espressocash_app/lib/features/ramp/widgets/on_ramp_deposit_widget.dart
Fixes tap area for "View MoneyGram transfer instructions" button.
Fixes background cropping.
> fix: moneygram deposit screen updates

- packages/espressocash_app/lib/features/wallet_flow/screens/wallet_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- check balance before Pay creation
- shows messages if lacking funds
Fixes #1596
<details>
https://github.com/user-attachments/assets/37ba1d35-70d3-4651-906b-fe83d0f0996b
</details>
> feat: check balance before Pay creation

- packages/espressocash_app/lib/features/ramp/partners/moneygram/widgets/launch.dart
moneygram withdraw fee currency
> fix: moneygram withdraw fee currency

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/ambassador_referral.dart
- packages/espressocash_api/lib/src/dto/ambassador_referral.freezed.dart
- packages/espressocash_api/lib/src/dto/ambassador_referral.g.dart
- packages/espressocash_api/lib/src/dto/fiat_rate.freezed.dart
- packages/espressocash_api/lib/src/dto/scalex.freezed.dart
- packages/espressocash_api/lib/src/exception.dart
- packages/espressocash_api/lib/src/exception.g.dart
> feat: add referral api

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/ambassador_stats.dart
- packages/espressocash_api/lib/src/dto/ambassador_stats.freezed.dart
- packages/espressocash_api/lib/src/dto/ambassador_stats.g.dart
> feat: ambassador stats endpoint

- packages/espressocash_app/android/gradle.properties
Fixes intercom webview crash in Android.
> fix: android intercom crash

- packages/espressocash_app/lib/features/kyc_sharing/screens/kyc_status_screen.dart
- packages/espressocash_app/lib/ui/info_list.dart
Updates icon of kyc status screen for pending state
> feat: update kyc status screen

- packages/espressocash_app/lib/features/stellar_recovery/service/recovery_service.dart
fixes stellar recovery amount calculation
> fix: recovery amount

- packages/espressocash_app/lib/features/conversion_rates/data/jupiter_client.dart
- packages/espressocash_app/lib/features/conversion_rates/data/repository.dart
- packages/espressocash_app/lib/features/tokens/token.dart
update to Jupiter price api v2 (https://station.jup.ag/docs/apis/price-api-v2)
> feat: update jupiter price api

- packages/espressocash_app/lib/features/kyc_sharing/screens/basic_information_screen.dart
- packages/espressocash_app/lib/features/kyc_sharing/screens/kyc_camera_screen.dart
- change camera resolution to veryHigh
- check disclaimer for existing user
> feat: update kyc camera resolution

- packages/espressocash_app/lib/features/ramp/partners/kyc/services/brij_on_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart
- packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart
- packages/espressocash_app/lib/features/ramp/services/off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/services/on_ramp_order_service.dart
- Remove completed orders from pending
- Add ability to delete failed orders
Related to https://github.com/espresso-cash/espresso-cash-public/issues/1627
> fix: brij orders

- packages/espressocash_app/lib/features/kyc_sharing/screens/basic_information_screen.dart
Fix for incorrect bithdate timezone.
Related to https://github.com/espresso-cash/espresso-cash-public/issues/1627
> fix: incorrect timezone for birthdate

- packages/espressocash_app/lib/features/kyc_sharing/services/kyc_service.dart
- packages/espressocash_app/lib/features/kyc_sharing/utils/kyc_utils.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
Updates data handling related to kyc client new version.
> feat: update kyc client

- packages/espressocash_app/lib/features/kyc_sharing/data/kyc_repository.dart
- packages/espressocash_app/lib/features/kyc_sharing/services/kyc_service.dart
> feat: kyc fetch statuses

- packages/espressocash_app/lib/features/ramp/partners/kyc/widgets/launch.dart
> fix: pending kyc notice dialog

- packages/espressocash_app/lib/features/conversion_rates/data/jupiter_client.dart
> fix: jupiter price api

- packages/espressocash_app/lib/features/authenticated/screens/home_screen.dart
fixes navigation service error
> fix: navigation service

- packages/espressocash_app/lib/features/kyc_sharing/models/document_type.dart
Leave only Voter ID in the document selector.
> feat: update document types

- packages/espressocash_app/lib/features/ramp/widgets/partner_config.dart
add Brazil to Coinflow countries
> feat: Coinflow supported countries update

- packages/espressocash_app/lib/features/profile/widgets/share_section.dart
- packages/espressocash_app/lib/ui/web_view_screen.dart
Open link in twitter application.
<details>
<summary>Android</summary>
https://github.com/user-attachments/assets/b419eec6-e10e-4dcf-8a4c-00d46738925c
</details>
<details>
<summary>IOS</summary>
https://github.com/user-attachments/assets/af534cff-2ebf-4662-ba61-d243ba209a52
</details>
> feat: open link in twitter application

- packages/espressocash_app/lib/features/kyc_sharing/models/document_type.dart
- packages/espressocash_app/lib/features/kyc_sharing/utils/kyc_utils.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
Add NIN_V2 to available documents
> feat: new document type support

- .github/workflows/check_pr.yml
fixes failing workflow on testing sql migrations
> ci: add sql dependencies

- packages/solana/test/programs/compute_budget_program/program_test.dart
Fix for SetComputeUnitPrice test
> fix: SetComputeUnitPrice test

- packages/espressocash_app/lib/features/feature_flags/data/feature_flags_manager.dart
- packages/espressocash_app/lib/features/fees/services/fee_calculator.dart
- packages/espressocash_app/lib/features/ramp/services/off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/services/on_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/widgets/on_ramp_deposit_widget.dart
- packages/espressocash_app/lib/features/ramp/widgets/on_ramp_order_details.dart
- packages/espressocash_app/lib/features/ramp/widgets/partner_config.dart
- packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
- packages/espressocash_app/lib/features/ramp_partner/models/ramp_partner.dart
adds production scalex using brij behind feature flag
> feat: added scalex brij partner

- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_on_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/partners/brij/widgets/launch.dart
- packages/espressocash_app/lib/features/ramp/services/on_ramp_order_service.dart
> fix: passing correct partner

- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_on_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/services/extensions.dart
> feat: add brij logging

- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_off_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_on_ramp_order_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
- packages/espressocash_app/lib/features/ramp/services/extensions.dart
update sentry reporting to specfic ramp statuses
> feat: update ramp sentry reporting

- packages/jupiter_aggregator/lib/src/client.dart
- packages/jupiter_aggregator/lib/src/client.g.dart
- packages/jupiter_aggregator/lib/src/model.dart
- packages/jupiter_aggregator/lib/src/model.freezed.dart
- packages/jupiter_aggregator/lib/src/model.g.dart
- packages/jupiter_aggregator/pubspec.yaml
- updates swap and price api
- adds baseUrl and apiKey in param
> feat: update jupiter clients

- packages/espressocash_api/lib/src/dto/create_payment.dart
- packages/espressocash_api/lib/src/dto/create_payment.freezed.dart
- packages/espressocash_api/lib/src/dto/create_payment.g.dart
adds token mint address for direct payments
> feat: add mintAddress for direct payment endpoint

- packages/espressocash_api/lib/espressocash_api.dart
- packages/espressocash_api/lib/src/client.dart
- packages/espressocash_api/lib/src/client.g.dart
- packages/espressocash_api/lib/src/dto/moneygram.dart
- packages/espressocash_api/lib/src/dto/ramp.dart
- packages/espressocash_api/lib/src/dto/scalex.dart
- packages/espressocash_api/lib/src/dto/scalex.freezed.dart
- packages/espressocash_api/lib/src/dto/scalex.g.dart
> feat: add scalex brij fee endpoint

- packages/espressocash_app/lib/features/kyc_sharing/data/kyc_repository.dart
- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_on_ramp_order_service.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
Add wallet address to onRamp orders
> feat: add wallet address 

- packages/espressocash_app/lib/features/ramp/partners/coinflow/data/coinflow_api_client.dart
> feat: coinflow api dto

- packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart
- packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
> feat: updated brij ramp text

- packages/espressocash_app/ios/Podfile
- packages/espressocash_app/ios/Podfile.lock
- packages/espressocash_app/ios/Runner.xcodeproj/project.pbxproj
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
- fix build runner
- fix ios build
> fix: dependencies update

- packages/espressocash_app/lib/features/feature_flags/data/feature_flags_manager.dart
- packages/espressocash_app/lib/features/ramp/widgets/partner_config.dart
> feat: remove scalex

- packages/espressocash_app/lib/features/kyc_sharing/data/kyc_repository.dart
- packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_off_ramp_order_service.dart
> feat: update brij orders

- packages/espressocash_app/lib/features/country_picker/widgets/country_picker.dart
- packages/espressocash_app/lib/features/kyc_sharing/screens/personal_information_screen.dart
- packages/espressocash_app/lib/features/kyc_sharing/utils/kyc_utils.dart
- packages/espressocash_app/lib/features/profile/widgets/kyc_section.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/lib/ui/dob_text_field.dart
Add personal info to profile in readonly mode.
Fixes [issue](https://github.com/espresso-cash/brij-meta/issues/6)
> feat: add personal info to profile 

- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> feat: update brij client version

- packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart
Do not show insufficient funds error message for txError failure reason.
> fix: moneygram status mapping

- .github/workflows/check_pr.yml
- packages/espressocash_app/lib/features/kyc_sharing/data/kyc_repository.dart
- packages/espressocash_app/pubspec.lock
- packages/espressocash_app/pubspec.yaml
> feat: update brij client

- .github/workflows/check_pr.yml
- packages/espressocash_client/lib/src/espressocash_client.dart
- packages/espressocash_client/test/basic_test.dart
- packages/espressocash_client/test/dln_test.dart
- packages/espressocash_client/test/escrow_test.dart
- packages/espressocash_client/test/fee_test.dart
- packages/espressocash_client/test/moneygram_test.dart
- packages/espressocash_client/test/tokens_test.dart
- packages/espressocash_client/test/utils.dart
- updates ec client to expose login method
- init client with token
Related to https://github.com/espresso-cash/espresso-cash-meta/issues/14
> feat: expose login on ec client

- packages/espressocash_app/lib/features/fees/services/fee_calculator.dart
- packages/espressocash_app/lib/features/token_send/widgets/token_input.dart
- deducts transfer fee to SOL when max button is used
Fixes https://github.com/espresso-cash/espresso-cash-meta/issues/18
> fix: send max sol

- packages/espressocash_app/lib/features/conversion_rates/data/jupiter_client.dart
- updated jupiter base url to free tier
- updated price api to v3 ([v2 to be deprecated in 1 month](https://dev.jup.ag/docs/price-api/v2))
> fix: update jupiter price api

- packages/espressocash_app/lib/features/analytics/analytics_manager.dart
- packages/espressocash_app/lib/features/authenticated/screens/home_screen.dart
- packages/espressocash_app/lib/features/token_swap/models/quote_exception.dart
- packages/espressocash_app/lib/features/token_swap/screens/swap_details_screen.dart
- packages/espressocash_app/lib/features/token_swap/screens/swap_input_screen.dart
- packages/espressocash_app/lib/features/token_swap/screens/swap_review_screen.dart
- packages/espressocash_app/lib/features/token_swap/screens/token_picker_screen.dart
- packages/espressocash_app/lib/features/token_swap/service/quote_service.dart
- packages/espressocash_app/lib/features/token_swap/service/swap_service.dart
- packages/espressocash_app/lib/features/tokens/data/token_repository.dart
- packages/espressocash_app/lib/l10n/intl_en.arb
- packages/espressocash_app/test/features/tokens/data/token_repository_test.dart
- added swap on home screen tabs
- updated token selector: added popular coins by marketcap
- updated token selector: use search query instead of get all tokens
- better error handling
- updated analytics to add usdc value
<details>
https://github.com/user-attachments/assets/8c1ef54a-3bf5-4960-8b17-b555ca88ed81
</details>
> feat: token swap updates

- CLAUDE.md
Adding CLAUDE.MD for future AI PRs
Fixes #___
- [ x] PR is ready for review (if not, it should be a draft).
- [x ] PR title follows [Conventional Commits][1] guidelines.
- [ x] Screenshots/video added.
- [ x] Tests added.
- [x ] Self-review done.
> feat: Add claude code init file
