packages/solana/lib/src/rpc_client/rpc_client_extensions.dart, packages/solana/lib/src/spl_token/spl_token.dart, packages/solana/lib/src/wallet.dart, packages/solana/test/spl_token_test.dart
NOTE: This PR incidentally deals with the fact that the supply of a token is `uint64` and dart integers are signed `int64`, which is forcing us to use `BigInt` instead.
=> fix!: Use commitment when waiting for signature status

packages/solana/lib/solana.dart, packages/solana/lib/src/exceptions/transaction_exception.dart, packages/solana/lib/src/rpc_client/rpc_client.dart, packages/solana/lib/src/rpc_client/rpc_client_extensions.dart
`waitForSignatureStatus` throws `TransactionException`  in case of error instead of arbitraty object.
Also, exported exceptions from the library to use in client code.
=> fix: Throw TransactionException in waitForSignatureStatus

packages/solana/lib/src/programs/token_program/token_program.dart, packages/solana/lib/src/spl_token/spl_token.dart, packages/solana/lib/src/wallet.dart, packages/solana/test/rpc_client_test.dart, packages/solana/test/spl_token_test.dart, packages/solana/test/subscription_client_test.dart, packages/solana/test/wallet_test.dart
- `Wallet` is now an alias of `Ed25519HDKeyPair` (as a more semantical name).
- `RpcClient` and `SubscriptionClient` are no longer part of `SplToken`, they are passed as arguments to the methods that need them.
- `memo` is now an optional argument of `transfer*` methods (instead of separate methods).
=> refactor!: Update Wallet

packages/solana/lib/src/curve25519/compressed_edwards_y.dart, packages/solana/lib/src/curve25519/edwards_point.dart, packages/solana/lib/src/curve25519/extensions.dart, packages/solana/lib/src/curve25519/field_element.dart, packages/solana/lib/src/curve25519/sqrt_ratio_m1_result.dart, packages/solana/lib/src/helpers.dart
The behavior of the operators and methods in the [int](https://api.dart.dev/stable/1.10.1/dart-core/int-class.html) class differs between the Dart VM and Dart code compiled to JavaScript.
`curve25519` operations work with large int numbers, so the operations actually fail in JS.
Migrated `curve25519` to `BigInt` internally to fix this.
=> fix: Use BigInt for curve25519

packages/cryptoplease/lib/presentation/screens/authenticated/nft/nft_screen.dart, packages/cryptoplease/lib/presentation/screens/authenticated/wallet_screen.dart, packages/cryptoplease/lib/presentation/snackbars.dart, packages/cryptoplease/lib/presentation/utils.dart, packages/cryptoplease_ui/lib/cryptoplease_ui.dart, packages/cryptoplease_ui/lib/src/snackbar.dart, packages/cryptoplease_ui/storybook/lib/main.dart, packages/cryptoplease_ui/storybook/lib/stories/snackbar.dart
Snackbars are now in `cryptoplease_ui` package.
=> refactor: Extract snackbars to cryptoplease_ui

packages/cryptoplease/lib/presentation/screens/authenticated/send_flow/fungible_token/link_transfer_flow_screen.dart
Fix initial token parameter for link transfer.
=> fix: Pass initial token for link transfer

packages/solana/lib/src/rpc/dto/meta.dart, packages/solana/lib/src/rpc/dto/meta.g.dart
Ran into an issue while trying to fetch the following transaction with this library :
`4ZbnJUyNXTqSzN535p77fjsZEWC9fJWk3jBSLij8uuTh376mQjjviVUvuLFtFzDXGTsSHAjFAiViFAweLscrve8C`
Moreover, according to the [doc](https://docs.solana.com/developing/clients/jsonrpc-api#gettransaction), `innerInstructions` and `logMessages` are `<array|null>`
Edit: Not the same issue, but Buffer.fromuint64 is not supported in dart2js (web), and it looks like they aren't going to fix it. Unfortunately many utils like `TokenInstruction.transfer` will fail in web.
[https://github.com/dart-lang/sdk/issues/10275](https://github.com/dart-lang/sdk/issues/10275)
=> fix: Make Meta innerInstructions and logMessages nullable

packages/solana/lib/src/subscription_client/subscription_client.dart
Previous implementation was missing `encoding` param.
https://docs.solana.com/developing/clients/jsonrpc-api#accountsubscribe
N/A.
=> fix: add `encoding` to `accountSubscribe`

packages/solana/lib/src/exceptions/rpc_timeout_exception.dart, packages/solana/lib/src/rpc/json_rpc_client.dart, packages/solana/lib/src/rpc/json_rpc_request.dart, packages/solana/test/rpc_client_test.dart
Added method names to `RpcTimeoutException` for easier debugging, e.g.
```
TimeoutException after 0:00:00.000000: RPC call getTransactionCount timed out.
TimeoutException after 0:00:00.000000: RPC call [getTransaction, getTransaction] timed out.
```
As per discussion here: https://github.com/cryptoplease/cryptoplease-dart/pull/285#issuecomment-1146707928
=> feat: Add method name to RpcTimeoutException

packages/cryptoplease/lib/bl/swap_tokens/transaction/swap_transaction_bloc.dart, packages/cryptoplease/lib/presentation/screens/authenticated/home_tabs_screen.dart, packages/cryptoplease/lib/presentation/screens/authenticated/swap_tokens/components/token_dropdown.dart, packages/cryptoplease/lib/presentation/screens/authenticated/swap_tokens/screens/swap_token_order_screen.dart, packages/cryptoplease/lib/presentation/screens/authenticated/swap_tokens/screens/swap_token_selector_screen.dart, packages/cryptoplease_ui/lib/src/button.dart
=> fix: improves swap ux flow

packages/cryptoplease/lib/app/components/token_fiat_input_widget/enter_amount_keypad.dart, packages/cryptoplease/lib/features/swap_tokens/presentation/components/swap_header_widget.dart, packages/cryptoplease/lib/features/swap_tokens/presentation/screens/swap_token_order_screen.dart
- Fixes keyboard visibility on swap page
<details><summary>Keyboard visibility in a 4.7'' device</summary>
</details>
Fixes #314 
=> fix: swap keyboard above navbar

packages/cryptoplease/lib/app/screens/dynamic_links/install_link_manager.dart
Fixed iOS deeplink parsing on app start, it should work not only on the first launch.
=> fix: Fix iOS deeplink parsing on start

packages/cryptoplease_link/lib/src/constants.dart, packages/cryptoplease_link/lib/src/handlers/common_link_handler.dart
- Uses deeplink instead of universal link for iOS and Android
<details><summary>Using Chrome</summary>
https://user-images.githubusercontent.com/19499575/179419869-faf1840a-1fd4-4675-9579-d8f2b2e51092.mp4
</details>
<details><summary>Using Safari</summary>
https://user-images.githubusercontent.com/19499575/179419873-f3801858-f124-4a6b-b7c9-5e15224e7d9e.mp4
</details>
=> feat: mapping universal link to deeplink

packages/cryptoplease/lib/core/presentation/token_selector_screen.dart
Wrapped SliverList widget in the `TokenList` with SliverPadding and provided it a bottom padding value of 64.
Fixes #389 
=> fix: add padding at the bottom of 'Select Token' list

packages/cryptoplease/lib/features/incoming_split_key_payment/bl/models.dart
Added default version value to `SplitKeyIncomingFirstPart`.
=> fix: add default value for version

packages/cryptoplease/lib/features/swap_tokens/bl/selector/swap_selector_bloc.dart, packages/cryptoplease/lib/features/swap_tokens/bl/swap_exception.dart, packages/cryptoplease/lib/features/swap_tokens/bl/transaction/swap_transaction_bloc.dart, packages/cryptoplease/lib/features/swap_tokens/presentation/screens/swap_token_order_screen.dart, packages/cryptoplease/lib/features/swap_tokens/presentation/screens/swap_token_process_screen.dart, packages/cryptoplease/lib/features/swap_tokens/presentation/swap_token_flow.dart, packages/cryptoplease/lib/main.dart, packages/cryptoplease/pubspec.lock, packages/cryptoplease/pubspec.yaml, packages/cryptoplease_link/cryptoplease_api/lib/cryptoplease_api.dart, packages/cryptoplease_link/cryptoplease_api/pubspec.yaml, packages/cryptoplease_link/pubspec.lock
- Move Jupiter API lib to Cryptoplease API package
First step to resolve on #448
=> refactor: move jupiter client to cryptoplease_api package

packages/cryptoplease/lib/app/components/recovery_phrase_text_view.dart
- Adjust copy button text size to align vertically
Fixes #473
=> fix: adjusted vertical align for copy button

packages/cryptoplease/assets/icons/investments.svg, packages/cryptoplease/lib/ui/navigation_bar/navigation_button.dart
- Fixes navigation bar icon arrangement
Fixes #535 
=> fix: navigation bar icons

packages/cryptoplease/lib/app/components/share_message_wrapper.dart
- Fixes share link layout issues
<details><summary>Screenshots</summary>
</details>
Fixes #536 
=> fix: share link layout margin

packages/cryptoplease/lib/ui/navigation_bar/navigation_button.dart
- Amends PR #540
<details><summary>Screenshots</summary>
</details>
Fixes #535 
=> fix: nav bar icon size

packages/cryptoplease/lib/features/outgoing_direct_payments/presentation/odp_header.dart
- Added horizontal padding on input amount
Fixes #552
=> fix: add horizontal padding on input amount

packages/cryptoplease/lib/features/payment_request/src/presentation/link_details/components/share_link.dart, packages/cryptoplease/lib/features/payment_request/src/presentation/link_details/components/share_qr_code.dart, packages/cryptoplease/lib/features/payment_request/src/presentation/link_details/share_request.dart, packages/cryptoplease/pubspec.lock
- Updated request page padding
- Removed QR image scroll
Fixes #599 
Fixes #600 
https://user-images.githubusercontent.com/28533130/200328457-0bfe5934-83b9-4ac6-8b0a-44641bd45ac7.mp4
=> fix: update request page layout

packages/cryptoplease/lib/core/transactions/tx_sender.dart, packages/cryptoplease/lib/features/incoming_split_key_payments/src/bl/incoming_split_key_payment.dart, packages/cryptoplease/lib/features/incoming_split_key_payments/src/bl/iskp_bloc.dart, packages/cryptoplease/lib/features/incoming_split_key_payments/src/bl/iskp_repository.dart, packages/cryptoplease/lib/features/outgoing_direct_payments/src/bl/bloc.dart, packages/cryptoplease/lib/features/outgoing_direct_payments/src/bl/outgoing_direct_payment.dart, packages/cryptoplease/lib/features/outgoing_direct_payments/src/bl/repository.dart, packages/cryptoplease/lib/features/outgoing_split_key_payments/src/bl/bloc.dart, packages/cryptoplease/lib/features/outgoing_split_key_payments/src/bl/outgoing_split_key_payment.dart, packages/cryptoplease/lib/features/outgoing_split_key_payments/src/bl/repository.dart, packages/cryptoplease/test/core/transactions/tx_sender_test.dart, packages/solana/test/metaplex/instructions/create_metadata_account_test.dart
If there was an error during waiting for tx status, and user retries after some time, it would never succeed because no status change would be reported. This PR check that the tx already exists on the blockchain and checks its status. If the tx doesn't exist and its blockhash is not valid anymore, it's safe to assume that tx has failed.
=> fix: TxSender correctly waits for old txs

packages/solana/lib/src/programs/token_program/instruction.dart, packages/solana/test/programs/token_program/token_program_test.dart
I have managed to pass the `newAuthority`  parameter as optional on the `TokenInstruction class`. I also added a test but failed to run the test since I am facing some network connection exceptions, saying "The remote computer refused the network connection."
Fixes #578 
=> fix: new authority is optional in SetAuthority

packages/cryptoplease/lib/features/app_lock/src/presentation/app_lock_disable_screen.dart, packages/cryptoplease/lib/features/app_lock/src/presentation/app_lock_enable_screen.dart
- added back button for app lock pages
=> fix: add back button in app lock

packages/cryptoplease/lib/core/accounts/module.dart, packages/cryptoplease/lib/core/callback.dart, packages/cryptoplease/lib/features/activities/module.dart, packages/cryptoplease/lib/features/investments/module.dart, packages/cryptoplease/lib/features/payment_request/module.dart
`LogoutListener` callback needs `BuildContext` to retrieve dependencies.
=> fix: add BuildContext to LogoutListener callback

packages/cryptoplease/lib/features/outgoing_direct_payments/src/bl/bloc.dart, packages/cryptoplease/pubspec.lock
Reference was not saved, so when the payment failed and retried, no information about reference was passed.
=> fix: save reference in OuggoingDirectPayment

packages/solana/lib/src/rpc/dto/perf_sample.dart, packages/solana/lib/src/rpc/dto/perf_sample.g.dart
The Solana RPC call getRecentPerformanceSamples returns a result with a field named `samplePeriodSecs` while the lib tries to parse a field named `samplePeriodSec`. 
Solana doc with sample result: https://docs.solana.com/developing/clients/jsonrpc-api#getrecentperformancesamples
=> fix: correct name of JSON field in getRecentPerformanceSamples result

packages/cryptoplease/lib/features/activities/src/widgets/swap_tile.dart
- Swap tile title and icon is displayed correctly based on the input type and operation.
</details>
=> fix: swap tile copy in transaction list

packages/cryptoplease/lib/features/swap/src/create_swap/components/swap_fee.dart, packages/cryptoplease/lib/features/swap/src/create_swap/components/token_dropdown.dart, packages/cryptoplease/lib/features/swap/src/create_swap/create_swap_screen.dart, packages/cryptoplease/lib/features/swap/src/flow.dart, packages/cryptoplease/lib/l10n/app_en.arb
- Minor improvements for swap screen
</details>
Fixes #729 
=> feat: minor improvements for swap screen

packages/solana/lib/src/programs/associated_token_account_program/solana_client_ext.dart, packages/solana/lib/src/rpc/dto/account.dart, packages/solana/lib/src/rpc/dto/account.g.dart, packages/solana/lib/src/rpc/helpers.dart
Fixes parsing `rentEpoch` as it's represented by `u64`. See https://github.com/solana-labs/solana/pull/29528
=> fix!: ProgramAccount.rentEpoch is now BigInt

packages/espressocash_app/lib/features/popular_tokens/widgets/popular_token_list.dart, packages/espressocash_app/pubspec.lock
- Fix token price overflow for popular crypto items on investment screen
<details><summary>Bug evidence</summary>
</details>
Added some screenshots from other phones (iPhone 14 Pro Max, iPhone SE 3rd gen) to ensure it did not break on those.
</details>
=> fix: token price overflow on investment screen

packages/espressocash_app/lib/features/onboarding/widgets/onboarding_notice.dart
Added `RepaintBoundary` to `OnboardingNotice` to prevent repainting the whole screen due to the animation.
=> perf: add RepaintBoundary to OnboardingNotice

packages/espressocash_backend/lib/src/swap/jupiter_repository.dart
Add support for legacy tx on swap (related to https://github.com/espresso-cash/espresso-cash-public/pull/792)
=> feat: use asLegacyTransaction for jupiter swap

packages/espressocash_app/lib/features/outgoing_split_key_payments/src/widgets/oskp_screen.dart
When clicking back button on share link screen for first time, go directly to home screen tabs
https://user-images.githubusercontent.com/28533130/219415760-083b5dfe-5dde-4163-8ba2-ca57aa79adad.mp4
=> feat: pop status screen when going to share screen for the first time

packages/espressocash_app/lib/app/screens/authenticated/profile/components/danger_section.dart, packages/espressocash_app/lib/ui/dialogs.dart
- Sets confirmation label as parameter on confirmation dialog
=> fix: confirmation dialog label

packages/espressocash_app/lib/ui/dialogs.dart
- Increases dim in the background;
- Changes font size for dialogs and bottom sheets.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
=> feat: improve dialogs ui

packages/espressocash_app/lib/app/screens/authenticated/wallet_flow/wallet_main_screen.dart
Expand qr button tap size in wallet screen
Fixes #833
Note: Green indicator not visible, for debugging purposes only to show tap area
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
=> fix: expand qr scanner button tap size

packages/solana_seed_vault/lib/src/extensions.dart, packages/solana_seed_vault/lib/src/seed_vault.dart
- Sets notification stream to be broadcast instead of single-subscriber;
- Adds `AccountFilter` as parameter when retrieving parsed seeds. 
=> fix: seed vault notification stream, account filter for parsed seeds

packages/espressocash_app/lib/app/screens/authenticated/profile/components/learning_section.dart, packages/espressocash_app/lib/app/screens/authenticated/profile/profile_screen.dart
- Remove duplicate "Edit Profile" menu option;
- Rename `AboutSection` to `LearningSection` to keep consistency.
</details>
=> feat: remove duplicate edit profile menu option

packages/espressocash_app/lib/features/incoming_split_key_payments/src/widgets/first_part_qr_screen.dart, packages/espressocash_app/lib/features/qr_scanner/src/widgets/qr_scanner_screen.dart, packages/espressocash_app/lib/features/qr_scanner/widgets/build_context_ext.dart
Send manually button is not shown when the user open the scanner after the first QR code is scanned.
=> feat: don't show manual input button after first qr scanned

packages/espressocash_app/lib/features/outgoing_split_key_payments/src/bl/oskp_service.dart
Manual cancellation tx should be signed with escrow key.
=> fix: correctly sign old cancellation tx

packages/espressocash_app/lib/core/presentation/format_amount.dart
- Sets max digits to crypto amount when formatted 
</details>
Fixes #956 
=> feat: truncate usdc amount on messages

packages/espressocash_app/lib/features/token_details/src/repository.dart, packages/espressocash_app/lib/features/token_details/src/token_details.dart, packages/espressocash_app/lib/features/token_details/src/widgets/token_details_widget.dart, packages/espressocash_app/lib/features/token_details/widgets/token_details_screen.dart
- Add l10n support for token details page
**Note**: Coingecko returns an English description for most of keys in the token description object, so localization won't be effective either way in many cases.
</details>
=> feat: add coingecko l10n support for token details page

packages/solana/lib/src/rpc/client.dart, packages/solana/lib/src/rpc/client.rpc.dart
Currently, getFeeForMessage throws an exception when the result comes back. The response isn't being parsed correctly. This patch fixes this issue and returns the correct fee value integer
Fixes #___
=> fix: getFeeForMessage response parsing

packages/espressocash_app/lib/features/ramp/data/on_ramp_order_service.dart, packages/espressocash_app/lib/features/ramp/src/widgets/partners/kado.dart
redirect to on ramp status screen after kado onramp
<details>
https://github.com/espresso-cash/espresso-cash-public/assets/28533130/f5d5fc9c-cc88-45e5-92a0-50d5254250ba
</details>
=> feat: redirect after kado onramp

packages/espressocash_app/lib/features/ramp/widgets/ramp_buttons.dart
add Guardarian partner for US onramp
Fixes #1228
<details>
</details>
=> feat: add Guardarian partner for US onramp

packages/espressocash_app/lib/features/outgoing_dln_payments/screens/details_screen.dart, packages/espressocash_app/lib/features/ramp/screens/off_ramp_order_screen.dart, packages/espressocash_app/lib/features/ramp/screens/on_ramp_order_screen.dart, packages/espressocash_app/lib/ui/partner_order_id.dart
make order id copyable
Fixes #1269
=> feat: make order id copyable

packages/jupiter_aggregator/README.md, packages/jupiter_aggregator/lib/src/client.dart, packages/jupiter_aggregator/lib/src/client.g.dart
1. Makes the Jupiter Swap V6 API base URL configurable.
2. Changes default URL to URL with higher rate limits.
3. Updates the README.
=> feat: make Jupiter API configurable via ENV vars

packages/espressocash_app/lib/features/dynamic_links/widgets/dynamic_link_handler.dart
fixes bug that dynamic links wont trigger on cold app start
Fixes #1370
=> fix: dynamic links on cold start

packages/espressocash_app/lib/features/qr_scanner/widgets/qr_scanner_background.dart
=> fix: camera overlay rendering

packages/espressocash_app/lib/features/activities/widgets/common_tile.dart
- show proper tx status in common tile
- use black text for 0 amount tiles
Fixes #1439
=> fix: show proper tx status for common tile

packages/solana/lib/src/solana_pay/solana_client_ext.dart
adds ignoreSignerVerification on processSolanaPayTransactionRequest. used when wallet has not resigned the tx prior to validation 
=> feat: add ignoreSignerVerification on processSolanaPayTransactionRequest

packages/espressocash_app/lib/features/conversion_rates/data/repository.dart
fixes wrong SOL amount. happens when user has sol and wrapped sol, only matching first on either.
=> fix: sol conversion matching

packages/solana/lib/src/rpc/dto/return_data.dart, packages/solana/lib/src/rpc/dto/return_data.g.dart
Update `ReturnData` serialization to accept both `'data'` and `['data', 'base64']`.
Fixes #1460
=> fix: ReturnData serialization

.github/workflows/check_pr.yml
updates deprecated upload-artifact version (https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/)
=> ci: update upload-artifact

packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_off_ramp_service.dart, packages/espressocash_app/lib/features/ramp/partners/moneygram/service/moneygram_on_ramp_service.dart
fixes an edge case where its possible that the refund transaction gets called twice (ie closing the app before poll is done)
=> fix: moneygram bridge fix

packages/solana/lib/src/programs/associated_token_account_program/solana_client_ext.dart
- pass the tokenProgramId to the createAccount method in the createAssociatedTokenAccount method.
Related to: https://github.com/espresso-cash/espresso-cash-public/issues/1657
=> fix: pass tokenProgramId to createAccount method in createAssociatedTokenAccount

packages/solana/lib/src/rpc/extension.dart, packages/solana/test/rpc_client_test.dart
Add new methods for fetching multiple txs for multiple accounts in 1 call.
=> feat: fetching multiple txs for multiple accounts

packages/solana/lib/src/programs/token_program/solana_client_ext.dart
The transferSplToken method doesn't support the token 2022 program. 
Fixes #___
=> fix: transferSplToken not supporting different program types

packages/espressocash_app/lib/features/kyc_sharing/data/kyc_repository.dart, packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_off_ramp_order_service.dart, packages/espressocash_app/lib/features/ramp/partners/brij/services/brij_on_ramp_order_service.dart, packages/espressocash_app/pubspec.lock, packages/espressocash_app/pubspec.yaml
Send fiat and crypto in decimal format
=> feat: decimal format for brij order

packages/solana/lib/src/rpc/dto/account.dart, packages/solana/lib/src/rpc/dto/account.freezed.dart, packages/solana/lib/src/rpc/dto/account.g.dart, packages/solana/lib/src/rpc/dto/context.dart, packages/solana/lib/src/rpc/dto/context.freezed.dart, packages/solana/lib/src/rpc/dto/context.g.dart, packages/solana/lib/src/rpc/helpers.dart, packages/solana/test/rpc_client_test.dart
`BigInt`s were deserialized from `num` in the code base but serialized to `String`s. The type becomes incompatible when a cache layer stores the serialized data and deserializes them when reading from the cache.
=> feat: Allow parsing big number from string value

packages/espressocash_app/lib/features/token_details/screens/token_details_screen.dart
Removes rounding token amount in token details page.
Fixes https://github.com/espresso-cash/espresso-cash-meta/issues/15
<details><summary>Preview</summary>
</details>
=> fix: remove round token amount

packages/espressocash_app/lib/features/token_send/widgets/token_input.dart, packages/espressocash_app/lib/ui/number_formatter.dart
Fixes send token amount calculation with **,** separator
Fixes https://github.com/espresso-cash/espresso-cash-meta/issues/17
<details><summary>Preview</summary>
</details>
=> fix: send token separator input
